
#include <clang-c/Index.h>
#include <fstream>
#include <set>
#include <unordered_map>
#include <ytrace/ytrace.hpp>

std::string get_file_name(CXCursor cursor) {
  CXFile file;
  unsigned line, column, offset;
  // TODO check if the cursor is valid
  // check if source location is valid
  // check if the file is valid
  CXSourceLocation loc = clang_getCursorLocation(cursor);
  if (clang_Location_isFromMainFile(loc) == 0) {
    ydebug("Location is not from main file");
    return "";
  }
  clang_getExpansionLocation(loc, &file, &line, &column, &offset);
  CXString file_name = clang_getFileName(file);
  CXString abs = clang_File_tryGetRealPathName(file);

  std::string name = clang_getCString(abs);

  clang_disposeString(abs);
  clang_disposeString(file_name);
  return name;
}

struct Type {
  std::string name;  // Name of the type
  std::size_t size;  // Size of the type in bytes
  std::size_t align; // Alignment of the type in bytes
};

struct Field {
  std::string name;   // Name of the field
  std::string type;   // Type of the field
  std::size_t offset; // Offset of the field in the record
};

struct Record : public Type {
  std::vector<Field> fields; // Fields of the record
};

struct Enum : public Type {
  std::vector<std::pair<std::string, int>> values; // Values of the enum
  std::string underlying_type; // Underlying type of the enum
};

struct Typedef : public Type {};

struct FunctionProto : public Type {
  std::vector<std::string> arg_types; // Arguments of the function
};

/* function is not a type!, it has a type, FunctionProto*/
struct Function {
  std::string name;
  std::string type;
};

class CIndex {

  std::unordered_map<std::string, Enum> enums;
  std::unordered_map<std::string, Record> records;
  std::unordered_map<std::string, FunctionProto> function_protos;
  std::unordered_map<std::string, Typedef> typedefs;
  std::string unit; // The name of the translation unit

public:
  CIndex(std::string unit) : unit(unit) { ydebug("Cindex constructor called"); }
  void add_type(CXCursor cursor, CXType cursor_type) {

    CXSourceLocation loc = clang_getCursorLocation(cursor);
    if (clang_Location_isFromMainFile(loc) == 0) {
      return;
    }

    CXString type_spelling = clang_getTypeSpelling(cursor_type);
    CXString type_kind_spelling = clang_getTypeKindSpelling(cursor_type.kind);

    /*
    auto cursor_file = get_file_name(cursor);
    if (cursor_file != unit) {
      return;
    }
    */

    switch (cursor_type.kind) {
    case CXType_Enum:
      enums.insert(clang_getCString(type_spelling));
      break;
    case CXType_Record:
      records.insert(clang_getCString(type_spelling));
      break;
    case CXType_FunctionProto:
      functions.insert(clang_getCString(type_spelling));
      break;
    case CXType_Typedef:
      typedefs.insert(clang_getCString(type_spelling));
      break;
    case CXType_Pointer:
    case CXType_LValueReference:
    case CXType_RValueReference:
      add_type(cursor, clang_getPointeeType(cursor_type));
      break;
    }
    clang_disposeString(type_kind_spelling);
    clang_disposeString(type_spelling);
  }
  void dump(const char *filename);
};

void CIndex::dump(const char *filename) {
  std::ofstream ofs(filename);
  ofs << "// This file is generated by cindex.cpp" << std::endl;
  ofs << "// Do not edit this file manually." << std::endl;
  ofs << "// Translation unit: " << unit << std::endl;
  ofs << "// Enums: " << enums.size() << std::endl;
  ofs << "#include <array>" << std::endl;
  ofs << "#include <utility>" << std::endl;
  ofs << "#include \"dawn/webgpu.h\"" << std::endl;
  ofs << "#include \"helper.hpp\"" << std::endl;
  ofs << "" << std::endl;
  ofs << "constexpr std::array<std::pair<const char*, EnumHandler>, "
      << enums.size() << "> enums = {{" << std::endl;
  bool first = true;
  /*
  constexpr std::array<pair, const void*>, 1> all_records = {{
    {"struct AStruct", meta_ptr<AStruct>()}
  }};
  */

  for (const auto &e : enums) {
    if (!first) {
      ofs << ", " << std::endl;
    } else {
      first = false;
    }
    ofs << "     {\"" << e << "\", get_enum_handler<" << e << ">()}";
  }
  ofs << std::endl;
  ofs << "}};" << std::endl;

  for (const auto &r : records) {
    ofs << "template <>" << std::endl;
    ofs << "struct RecordMeta<" << r << "> {";
    ofs << "};" << std::endl << std::endl;
  }

  ofs << "constexpr std::array<std::pair<const char*, RecordHandler>, "
      << records.size() << "> records = {{" << std::endl;
  first = true;
  for (const auto &r : records) {
    if (!first) {
      ofs << ", " << std::endl;
    } else {
      first = false;
    }
    ofs << "     {\"" << r << "\", get_record_handler<" << r << ">()}";
  }
  ofs << std::endl;
  ofs << "}};" << std::endl;

  ofs << "constexpr std::array<std::pair<const char*, RecordHandler>, "
      << typedefs.size() << "> typedefs = {{" << std::endl;
  first = true;
  for (const auto &t : typedefs) {
    if (!first) {
      ofs << ", " << std::endl;
    } else {
      first = false;
    }
    ofs << "     {\"" << t << "\", get_typedef_handler<" << t << ">()}";
  }
  ofs << std::endl;
  ofs << "}};" << std::endl;

  for (const auto &f : functions) {
    // fprintf(file, "extern %s;\n", f.c_str());
  }

  // fclose(file);
}

int main(int argc, char **argv) {

  const char *args[] = {
      "-resource-dir",
      "/home/linuxbrew/.linuxbrew/Cellar/llvm/20.1.6/lib/clang/20",
      "-Xclang",
      "-internal-isystem",
      "/home/linuxbrew/.linuxbrew/Cellar/llvm/20.1.6/lib/clang/20/include",
      "-Xclang",
      "-internal-isystem",
      "/usr/local/include",
      "-Xclang",
      "-internal-isystem",
      "/usr/lib/gcc/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/include",
      "-Xclang",
      "-internal-externc-isystem",
      "/usr/include/x86_64-linux-gnu",
      "-Xclang",
      "-internal-externc-isystem",
      "/include",
      "-Xclang",
      "-internal-externc-isystem",
      "/usr/include"};

  CXIndex index = clang_createIndex(0, 0); // Create index
  //
  size_t nargs = sizeof(args) / sizeof(args[0]);

  CXTranslationUnit unit = clang_parseTranslationUnit(
      index, argv[1], args, nargs, NULL, 0, CXTranslationUnit_None);

  if (unit == nullptr) {
    yinfo("Unable to parse translation unit.");
    return 0;
  }
  CXCursor cursor = clang_getTranslationUnitCursor(
      unit); // Obtain a cursor at the root of the translation unit

  CXString unit_spelling = clang_getTranslationUnitSpelling(unit);
  CXFile file = clang_getFile(unit, clang_getCString(unit_spelling));
  CXString abs = clang_File_tryGetRealPathName(file);
  std::string name = clang_getCString(abs);
  clang_disposeString(abs);
  clang_disposeString(unit_spelling);
  CIndex cindex(name); // Create an instance of CIndex
  clang_visitChildren(
      cursor,
      [](CXCursor current_cursor, CXCursor parent, CXClientData client_data) {
        auto *cindex = static_cast<CIndex *>(client_data);
        CXType cursor_type = clang_getCursorType(current_cursor);
        cindex->add_type(current_cursor, cursor_type);
        return CXChildVisit_Recurse;
      },
      &cindex);

  cindex.dump("out.hpp");
}
