// This file is generated by cindex.cpp
// Do not edit this file manually.
// Translation unit: /home/misi/work/my/yconstexpr-private/test/include/dawn/webgpu.h
// Enums: 57
#include <array>
#include <utility>
#include "dawn/webgpu.h"
#include "helper.hpp"

constexpr std::array<std::pair<const char*, EnumHandler>, 57> enums = {{
     {"enum WGPUAdapterType", get_enum_handler<enum WGPUAdapterType>()}, 
     {"enum WGPUAddressMode", get_enum_handler<enum WGPUAddressMode>()}, 
     {"enum WGPUAlphaMode", get_enum_handler<enum WGPUAlphaMode>()}, 
     {"enum WGPUBackendType", get_enum_handler<enum WGPUBackendType>()}, 
     {"enum WGPUBlendFactor", get_enum_handler<enum WGPUBlendFactor>()}, 
     {"enum WGPUBlendOperation", get_enum_handler<enum WGPUBlendOperation>()}, 
     {"enum WGPUBufferBindingType", get_enum_handler<enum WGPUBufferBindingType>()}, 
     {"enum WGPUBufferMapState", get_enum_handler<enum WGPUBufferMapState>()}, 
     {"enum WGPUCallbackMode", get_enum_handler<enum WGPUCallbackMode>()}, 
     {"enum WGPUCompareFunction", get_enum_handler<enum WGPUCompareFunction>()}, 
     {"enum WGPUCompilationInfoRequestStatus", get_enum_handler<enum WGPUCompilationInfoRequestStatus>()}, 
     {"enum WGPUCompilationMessageType", get_enum_handler<enum WGPUCompilationMessageType>()}, 
     {"enum WGPUCompositeAlphaMode", get_enum_handler<enum WGPUCompositeAlphaMode>()}, 
     {"enum WGPUCreatePipelineAsyncStatus", get_enum_handler<enum WGPUCreatePipelineAsyncStatus>()}, 
     {"enum WGPUCullMode", get_enum_handler<enum WGPUCullMode>()}, 
     {"enum WGPUDeviceLostReason", get_enum_handler<enum WGPUDeviceLostReason>()}, 
     {"enum WGPUErrorFilter", get_enum_handler<enum WGPUErrorFilter>()}, 
     {"enum WGPUErrorType", get_enum_handler<enum WGPUErrorType>()}, 
     {"enum WGPUExternalTextureRotation", get_enum_handler<enum WGPUExternalTextureRotation>()}, 
     {"enum WGPUFeatureLevel", get_enum_handler<enum WGPUFeatureLevel>()}, 
     {"enum WGPUFeatureName", get_enum_handler<enum WGPUFeatureName>()}, 
     {"enum WGPUFilterMode", get_enum_handler<enum WGPUFilterMode>()}, 
     {"enum WGPUFrontFace", get_enum_handler<enum WGPUFrontFace>()}, 
     {"enum WGPUIndexFormat", get_enum_handler<enum WGPUIndexFormat>()}, 
     {"enum WGPULoadOp", get_enum_handler<enum WGPULoadOp>()}, 
     {"enum WGPULoggingType", get_enum_handler<enum WGPULoggingType>()}, 
     {"enum WGPUMapAsyncStatus", get_enum_handler<enum WGPUMapAsyncStatus>()}, 
     {"enum WGPUMipmapFilterMode", get_enum_handler<enum WGPUMipmapFilterMode>()}, 
     {"enum WGPUOptionalBool", get_enum_handler<enum WGPUOptionalBool>()}, 
     {"enum WGPUPopErrorScopeStatus", get_enum_handler<enum WGPUPopErrorScopeStatus>()}, 
     {"enum WGPUPowerPreference", get_enum_handler<enum WGPUPowerPreference>()}, 
     {"enum WGPUPredefinedColorSpace", get_enum_handler<enum WGPUPredefinedColorSpace>()}, 
     {"enum WGPUPresentMode", get_enum_handler<enum WGPUPresentMode>()}, 
     {"enum WGPUPrimitiveTopology", get_enum_handler<enum WGPUPrimitiveTopology>()}, 
     {"enum WGPUQueryType", get_enum_handler<enum WGPUQueryType>()}, 
     {"enum WGPUQueueWorkDoneStatus", get_enum_handler<enum WGPUQueueWorkDoneStatus>()}, 
     {"enum WGPURequestAdapterStatus", get_enum_handler<enum WGPURequestAdapterStatus>()}, 
     {"enum WGPURequestDeviceStatus", get_enum_handler<enum WGPURequestDeviceStatus>()}, 
     {"enum WGPUSType", get_enum_handler<enum WGPUSType>()}, 
     {"enum WGPUSamplerBindingType", get_enum_handler<enum WGPUSamplerBindingType>()}, 
     {"enum WGPUSharedFenceType", get_enum_handler<enum WGPUSharedFenceType>()}, 
     {"enum WGPUStatus", get_enum_handler<enum WGPUStatus>()}, 
     {"enum WGPUStencilOperation", get_enum_handler<enum WGPUStencilOperation>()}, 
     {"enum WGPUStorageTextureAccess", get_enum_handler<enum WGPUStorageTextureAccess>()}, 
     {"enum WGPUStoreOp", get_enum_handler<enum WGPUStoreOp>()}, 
     {"enum WGPUSubgroupMatrixComponentType", get_enum_handler<enum WGPUSubgroupMatrixComponentType>()}, 
     {"enum WGPUSurfaceGetCurrentTextureStatus", get_enum_handler<enum WGPUSurfaceGetCurrentTextureStatus>()}, 
     {"enum WGPUTextureAspect", get_enum_handler<enum WGPUTextureAspect>()}, 
     {"enum WGPUTextureDimension", get_enum_handler<enum WGPUTextureDimension>()}, 
     {"enum WGPUTextureFormat", get_enum_handler<enum WGPUTextureFormat>()}, 
     {"enum WGPUTextureSampleType", get_enum_handler<enum WGPUTextureSampleType>()}, 
     {"enum WGPUTextureViewDimension", get_enum_handler<enum WGPUTextureViewDimension>()}, 
     {"enum WGPUToneMappingMode", get_enum_handler<enum WGPUToneMappingMode>()}, 
     {"enum WGPUVertexFormat", get_enum_handler<enum WGPUVertexFormat>()}, 
     {"enum WGPUVertexStepMode", get_enum_handler<enum WGPUVertexStepMode>()}, 
     {"enum WGPUWGSLLanguageFeatureName", get_enum_handler<enum WGPUWGSLLanguageFeatureName>()}, 
     {"enum WGPUWaitStatus", get_enum_handler<enum WGPUWaitStatus>()}
}};
template <>
struct RecordMeta<struct WGPUAHardwareBufferProperties> {};
template <>
struct RecordMeta<struct WGPUAdapterImpl> {};
template <>
struct RecordMeta<struct WGPUAdapterInfo> {};
template <>
struct RecordMeta<struct WGPUAdapterPropertiesD3D> {};
template <>
struct RecordMeta<struct WGPUAdapterPropertiesMemoryHeaps> {};
template <>
struct RecordMeta<struct WGPUAdapterPropertiesSubgroupMatrixConfigs> {};
template <>
struct RecordMeta<struct WGPUAdapterPropertiesVk> {};
template <>
struct RecordMeta<struct WGPUBindGroupDescriptor> {};
template <>
struct RecordMeta<struct WGPUBindGroupEntry> {};
template <>
struct RecordMeta<struct WGPUBindGroupImpl> {};
template <>
struct RecordMeta<struct WGPUBindGroupLayoutDescriptor> {};
template <>
struct RecordMeta<struct WGPUBindGroupLayoutEntry> {};
template <>
struct RecordMeta<struct WGPUBindGroupLayoutImpl> {};
template <>
struct RecordMeta<struct WGPUBlendComponent> {};
template <>
struct RecordMeta<struct WGPUBlendState> {};
template <>
struct RecordMeta<struct WGPUBufferBindingLayout> {};
template <>
struct RecordMeta<struct WGPUBufferDescriptor> {};
template <>
struct RecordMeta<struct WGPUBufferHostMappedPointer> {};
template <>
struct RecordMeta<struct WGPUBufferImpl> {};
template <>
struct RecordMeta<struct WGPUBufferMapCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUChainedStruct> {};
template <>
struct RecordMeta<struct WGPUColor> {};
template <>
struct RecordMeta<struct WGPUColorTargetState> {};
template <>
struct RecordMeta<struct WGPUColorTargetStateExpandResolveTextureDawn> {};
template <>
struct RecordMeta<struct WGPUCommandBufferDescriptor> {};
template <>
struct RecordMeta<struct WGPUCommandBufferImpl> {};
template <>
struct RecordMeta<struct WGPUCommandEncoderDescriptor> {};
template <>
struct RecordMeta<struct WGPUCommandEncoderImpl> {};
template <>
struct RecordMeta<struct WGPUCompatibilityModeLimits> {};
template <>
struct RecordMeta<struct WGPUCompilationInfo> {};
template <>
struct RecordMeta<struct WGPUCompilationInfoCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUCompilationMessage> {};
template <>
struct RecordMeta<struct WGPUComputePassDescriptor> {};
template <>
struct RecordMeta<struct WGPUComputePassEncoderImpl> {};
template <>
struct RecordMeta<struct WGPUComputePipelineDescriptor> {};
template <>
struct RecordMeta<struct WGPUComputePipelineImpl> {};
template <>
struct RecordMeta<struct WGPUComputeState> {};
template <>
struct RecordMeta<struct WGPUConstantEntry> {};
template <>
struct RecordMeta<struct WGPUCopyTextureForBrowserOptions> {};
template <>
struct RecordMeta<struct WGPUCreateComputePipelineAsyncCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUCreateRenderPipelineAsyncCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUDawnAdapterPropertiesPowerPreference> {};
template <>
struct RecordMeta<struct WGPUDawnBufferDescriptorErrorInfoFromWireClient> {};
template <>
struct RecordMeta<struct WGPUDawnCacheDeviceDescriptor> {};
template <>
struct RecordMeta<struct WGPUDawnCompilationMessageUtf16> {};
template <>
struct RecordMeta<struct WGPUDawnDeviceAllocatorControl> {};
template <>
struct RecordMeta<struct WGPUDawnDrmFormatCapabilities> {};
template <>
struct RecordMeta<struct WGPUDawnDrmFormatProperties> {};
template <>
struct RecordMeta<struct WGPUDawnEncoderInternalUsageDescriptor> {};
template <>
struct RecordMeta<struct WGPUDawnFakeBufferOOMForTesting> {};
template <>
struct RecordMeta<struct WGPUDawnFakeDeviceInitializeErrorForTesting> {};
template <>
struct RecordMeta<struct WGPUDawnFormatCapabilities> {};
template <>
struct RecordMeta<struct WGPUDawnHostMappedPointerLimits> {};
template <>
struct RecordMeta<struct WGPUDawnInjectedInvalidSType> {};
template <>
struct RecordMeta<struct WGPUDawnRenderPassColorAttachmentRenderToSingleSampled> {};
template <>
struct RecordMeta<struct WGPUDawnShaderModuleSPIRVOptionsDescriptor> {};
template <>
struct RecordMeta<struct WGPUDawnTexelCopyBufferRowAlignmentLimits> {};
template <>
struct RecordMeta<struct WGPUDawnTextureInternalUsageDescriptor> {};
template <>
struct RecordMeta<struct WGPUDawnTogglesDescriptor> {};
template <>
struct RecordMeta<struct WGPUDawnWGSLBlocklist> {};
template <>
struct RecordMeta<struct WGPUDawnWireWGSLControl> {};
template <>
struct RecordMeta<struct WGPUDepthStencilState> {};
template <>
struct RecordMeta<struct WGPUDeviceDescriptor> {};
template <>
struct RecordMeta<struct WGPUDeviceImpl> {};
template <>
struct RecordMeta<struct WGPUDeviceLostCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUEmscriptenSurfaceSourceCanvasHTMLSelector> {};
template <>
struct RecordMeta<struct WGPUExtent2D> {};
template <>
struct RecordMeta<struct WGPUExtent3D> {};
template <>
struct RecordMeta<struct WGPUExternalTextureBindingEntry> {};
template <>
struct RecordMeta<struct WGPUExternalTextureBindingLayout> {};
template <>
struct RecordMeta<struct WGPUExternalTextureDescriptor> {};
template <>
struct RecordMeta<struct WGPUExternalTextureImpl> {};
template <>
struct RecordMeta<struct WGPUFragmentState> {};
template <>
struct RecordMeta<struct WGPUFuture> {};
template <>
struct RecordMeta<struct WGPUFutureWaitInfo> {};
template <>
struct RecordMeta<struct WGPUINTERNAL_HAVE_EMDAWNWEBGPU_HEADER> {};
template <>
struct RecordMeta<struct WGPUImageCopyExternalTexture> {};
template <>
struct RecordMeta<struct WGPUInstanceCapabilities> {};
template <>
struct RecordMeta<struct WGPUInstanceDescriptor> {};
template <>
struct RecordMeta<struct WGPUInstanceImpl> {};
template <>
struct RecordMeta<struct WGPULimits> {};
template <>
struct RecordMeta<struct WGPULoggingCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUMemoryHeapInfo> {};
template <>
struct RecordMeta<struct WGPUMultisampleState> {};
template <>
struct RecordMeta<struct WGPUOrigin2D> {};
template <>
struct RecordMeta<struct WGPUOrigin3D> {};
template <>
struct RecordMeta<struct WGPUPassTimestampWrites> {};
template <>
struct RecordMeta<struct WGPUPipelineLayoutDescriptor> {};
template <>
struct RecordMeta<struct WGPUPipelineLayoutImpl> {};
template <>
struct RecordMeta<struct WGPUPipelineLayoutPixelLocalStorage> {};
template <>
struct RecordMeta<struct WGPUPipelineLayoutStorageAttachment> {};
template <>
struct RecordMeta<struct WGPUPopErrorScopeCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUPrimitiveState> {};
template <>
struct RecordMeta<struct WGPUQuerySetDescriptor> {};
template <>
struct RecordMeta<struct WGPUQuerySetImpl> {};
template <>
struct RecordMeta<struct WGPUQueueDescriptor> {};
template <>
struct RecordMeta<struct WGPUQueueImpl> {};
template <>
struct RecordMeta<struct WGPUQueueWorkDoneCallbackInfo> {};
template <>
struct RecordMeta<struct WGPURenderBundleDescriptor> {};
template <>
struct RecordMeta<struct WGPURenderBundleEncoderDescriptor> {};
template <>
struct RecordMeta<struct WGPURenderBundleEncoderImpl> {};
template <>
struct RecordMeta<struct WGPURenderBundleImpl> {};
template <>
struct RecordMeta<struct WGPURenderPassColorAttachment> {};
template <>
struct RecordMeta<struct WGPURenderPassDepthStencilAttachment> {};
template <>
struct RecordMeta<struct WGPURenderPassDescriptor> {};
template <>
struct RecordMeta<struct WGPURenderPassDescriptorExpandResolveRect> {};
template <>
struct RecordMeta<struct WGPURenderPassDescriptorResolveRect> {};
template <>
struct RecordMeta<struct WGPURenderPassEncoderImpl> {};
template <>
struct RecordMeta<struct WGPURenderPassMaxDrawCount> {};
template <>
struct RecordMeta<struct WGPURenderPassPixelLocalStorage> {};
template <>
struct RecordMeta<struct WGPURenderPassStorageAttachment> {};
template <>
struct RecordMeta<struct WGPURenderPipelineDescriptor> {};
template <>
struct RecordMeta<struct WGPURenderPipelineImpl> {};
template <>
struct RecordMeta<struct WGPURequestAdapterCallbackInfo> {};
template <>
struct RecordMeta<struct WGPURequestAdapterOptions> {};
template <>
struct RecordMeta<struct WGPURequestAdapterWebGPUBackendOptions> {};
template <>
struct RecordMeta<struct WGPURequestAdapterWebXROptions> {};
template <>
struct RecordMeta<struct WGPURequestDeviceCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUSamplerBindingLayout> {};
template <>
struct RecordMeta<struct WGPUSamplerDescriptor> {};
template <>
struct RecordMeta<struct WGPUSamplerImpl> {};
template <>
struct RecordMeta<struct WGPUShaderModuleCompilationOptions> {};
template <>
struct RecordMeta<struct WGPUShaderModuleDescriptor> {};
template <>
struct RecordMeta<struct WGPUShaderModuleImpl> {};
template <>
struct RecordMeta<struct WGPUShaderSourceSPIRV> {};
template <>
struct RecordMeta<struct WGPUShaderSourceWGSL> {};
template <>
struct RecordMeta<struct WGPUSharedBufferMemoryBeginAccessDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedBufferMemoryDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedBufferMemoryEndAccessState> {};
template <>
struct RecordMeta<struct WGPUSharedBufferMemoryImpl> {};
template <>
struct RecordMeta<struct WGPUSharedBufferMemoryProperties> {};
template <>
struct RecordMeta<struct WGPUSharedFenceDXGISharedHandleDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceDXGISharedHandleExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceEGLSyncDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceEGLSyncExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceImpl> {};
template <>
struct RecordMeta<struct WGPUSharedFenceMTLSharedEventDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceMTLSharedEventExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceSyncFDDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceSyncFDExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceVkSemaphoreOpaqueFDDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceVkSemaphoreOpaqueFDExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedFenceVkSemaphoreZirconHandleDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedFenceVkSemaphoreZirconHandleExportInfo> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryAHardwareBufferDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryAHardwareBufferProperties> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryBeginAccessDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryD3DSwapchainBeginState> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryDXGISharedHandleDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryDmaBufDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryDmaBufPlane> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryEGLImageDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryEndAccessState> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryIOSurfaceDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryImpl> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryOpaqueFDDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryProperties> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryVkImageLayoutBeginState> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryVkImageLayoutEndState> {};
template <>
struct RecordMeta<struct WGPUSharedTextureMemoryZirconHandleDescriptor> {};
template <>
struct RecordMeta<struct WGPUStaticSamplerBindingLayout> {};
template <>
struct RecordMeta<struct WGPUStencilFaceState> {};
template <>
struct RecordMeta<struct WGPUStorageTextureBindingLayout> {};
template <>
struct RecordMeta<struct WGPUStringView> {};
template <>
struct RecordMeta<struct WGPUSubgroupMatrixConfig> {};
template <>
struct RecordMeta<struct WGPUSupportedFeatures> {};
template <>
struct RecordMeta<struct WGPUSupportedWGSLLanguageFeatures> {};
template <>
struct RecordMeta<struct WGPUSurfaceCapabilities> {};
template <>
struct RecordMeta<struct WGPUSurfaceColorManagement> {};
template <>
struct RecordMeta<struct WGPUSurfaceConfiguration> {};
template <>
struct RecordMeta<struct WGPUSurfaceDescriptor> {};
template <>
struct RecordMeta<struct WGPUSurfaceDescriptorFromWindowsCoreWindow> {};
template <>
struct RecordMeta<struct WGPUSurfaceDescriptorFromWindowsUWPSwapChainPanel> {};
template <>
struct RecordMeta<struct WGPUSurfaceDescriptorFromWindowsWinUISwapChainPanel> {};
template <>
struct RecordMeta<struct WGPUSurfaceImpl> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceAndroidNativeWindow> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceMetalLayer> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceWaylandSurface> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceWindowsHWND> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceXCBWindow> {};
template <>
struct RecordMeta<struct WGPUSurfaceSourceXlibWindow> {};
template <>
struct RecordMeta<struct WGPUSurfaceTexture> {};
template <>
struct RecordMeta<struct WGPUTexelCopyBufferInfo> {};
template <>
struct RecordMeta<struct WGPUTexelCopyBufferLayout> {};
template <>
struct RecordMeta<struct WGPUTexelCopyTextureInfo> {};
template <>
struct RecordMeta<struct WGPUTextureBindingLayout> {};
template <>
struct RecordMeta<struct WGPUTextureBindingViewDimensionDescriptor> {};
template <>
struct RecordMeta<struct WGPUTextureDescriptor> {};
template <>
struct RecordMeta<struct WGPUTextureImpl> {};
template <>
struct RecordMeta<struct WGPUTextureViewDescriptor> {};
template <>
struct RecordMeta<struct WGPUTextureViewImpl> {};
template <>
struct RecordMeta<struct WGPUUncapturedErrorCallbackInfo> {};
template <>
struct RecordMeta<struct WGPUVertexAttribute> {};
template <>
struct RecordMeta<struct WGPUVertexBufferLayout> {};
template <>
struct RecordMeta<struct WGPUVertexState> {};
template <>
struct RecordMeta<struct WGPUYCbCrVkDescriptor> {};
constexpr std::array<std::pair<const char*, RecordHandler>, 200> records = {{
     {"struct WGPUAHardwareBufferProperties", get_record_handler<struct WGPUAHardwareBufferProperties>()}, 
     {"struct WGPUAdapterImpl", get_record_handler<struct WGPUAdapterImpl>()}, 
     {"struct WGPUAdapterInfo", get_record_handler<struct WGPUAdapterInfo>()}, 
     {"struct WGPUAdapterPropertiesD3D", get_record_handler<struct WGPUAdapterPropertiesD3D>()}, 
     {"struct WGPUAdapterPropertiesMemoryHeaps", get_record_handler<struct WGPUAdapterPropertiesMemoryHeaps>()}, 
     {"struct WGPUAdapterPropertiesSubgroupMatrixConfigs", get_record_handler<struct WGPUAdapterPropertiesSubgroupMatrixConfigs>()}, 
     {"struct WGPUAdapterPropertiesVk", get_record_handler<struct WGPUAdapterPropertiesVk>()}, 
     {"struct WGPUBindGroupDescriptor", get_record_handler<struct WGPUBindGroupDescriptor>()}, 
     {"struct WGPUBindGroupEntry", get_record_handler<struct WGPUBindGroupEntry>()}, 
     {"struct WGPUBindGroupImpl", get_record_handler<struct WGPUBindGroupImpl>()}, 
     {"struct WGPUBindGroupLayoutDescriptor", get_record_handler<struct WGPUBindGroupLayoutDescriptor>()}, 
     {"struct WGPUBindGroupLayoutEntry", get_record_handler<struct WGPUBindGroupLayoutEntry>()}, 
     {"struct WGPUBindGroupLayoutImpl", get_record_handler<struct WGPUBindGroupLayoutImpl>()}, 
     {"struct WGPUBlendComponent", get_record_handler<struct WGPUBlendComponent>()}, 
     {"struct WGPUBlendState", get_record_handler<struct WGPUBlendState>()}, 
     {"struct WGPUBufferBindingLayout", get_record_handler<struct WGPUBufferBindingLayout>()}, 
     {"struct WGPUBufferDescriptor", get_record_handler<struct WGPUBufferDescriptor>()}, 
     {"struct WGPUBufferHostMappedPointer", get_record_handler<struct WGPUBufferHostMappedPointer>()}, 
     {"struct WGPUBufferImpl", get_record_handler<struct WGPUBufferImpl>()}, 
     {"struct WGPUBufferMapCallbackInfo", get_record_handler<struct WGPUBufferMapCallbackInfo>()}, 
     {"struct WGPUChainedStruct", get_record_handler<struct WGPUChainedStruct>()}, 
     {"struct WGPUColor", get_record_handler<struct WGPUColor>()}, 
     {"struct WGPUColorTargetState", get_record_handler<struct WGPUColorTargetState>()}, 
     {"struct WGPUColorTargetStateExpandResolveTextureDawn", get_record_handler<struct WGPUColorTargetStateExpandResolveTextureDawn>()}, 
     {"struct WGPUCommandBufferDescriptor", get_record_handler<struct WGPUCommandBufferDescriptor>()}, 
     {"struct WGPUCommandBufferImpl", get_record_handler<struct WGPUCommandBufferImpl>()}, 
     {"struct WGPUCommandEncoderDescriptor", get_record_handler<struct WGPUCommandEncoderDescriptor>()}, 
     {"struct WGPUCommandEncoderImpl", get_record_handler<struct WGPUCommandEncoderImpl>()}, 
     {"struct WGPUCompatibilityModeLimits", get_record_handler<struct WGPUCompatibilityModeLimits>()}, 
     {"struct WGPUCompilationInfo", get_record_handler<struct WGPUCompilationInfo>()}, 
     {"struct WGPUCompilationInfoCallbackInfo", get_record_handler<struct WGPUCompilationInfoCallbackInfo>()}, 
     {"struct WGPUCompilationMessage", get_record_handler<struct WGPUCompilationMessage>()}, 
     {"struct WGPUComputePassDescriptor", get_record_handler<struct WGPUComputePassDescriptor>()}, 
     {"struct WGPUComputePassEncoderImpl", get_record_handler<struct WGPUComputePassEncoderImpl>()}, 
     {"struct WGPUComputePipelineDescriptor", get_record_handler<struct WGPUComputePipelineDescriptor>()}, 
     {"struct WGPUComputePipelineImpl", get_record_handler<struct WGPUComputePipelineImpl>()}, 
     {"struct WGPUComputeState", get_record_handler<struct WGPUComputeState>()}, 
     {"struct WGPUConstantEntry", get_record_handler<struct WGPUConstantEntry>()}, 
     {"struct WGPUCopyTextureForBrowserOptions", get_record_handler<struct WGPUCopyTextureForBrowserOptions>()}, 
     {"struct WGPUCreateComputePipelineAsyncCallbackInfo", get_record_handler<struct WGPUCreateComputePipelineAsyncCallbackInfo>()}, 
     {"struct WGPUCreateRenderPipelineAsyncCallbackInfo", get_record_handler<struct WGPUCreateRenderPipelineAsyncCallbackInfo>()}, 
     {"struct WGPUDawnAdapterPropertiesPowerPreference", get_record_handler<struct WGPUDawnAdapterPropertiesPowerPreference>()}, 
     {"struct WGPUDawnBufferDescriptorErrorInfoFromWireClient", get_record_handler<struct WGPUDawnBufferDescriptorErrorInfoFromWireClient>()}, 
     {"struct WGPUDawnCacheDeviceDescriptor", get_record_handler<struct WGPUDawnCacheDeviceDescriptor>()}, 
     {"struct WGPUDawnCompilationMessageUtf16", get_record_handler<struct WGPUDawnCompilationMessageUtf16>()}, 
     {"struct WGPUDawnDeviceAllocatorControl", get_record_handler<struct WGPUDawnDeviceAllocatorControl>()}, 
     {"struct WGPUDawnDrmFormatCapabilities", get_record_handler<struct WGPUDawnDrmFormatCapabilities>()}, 
     {"struct WGPUDawnDrmFormatProperties", get_record_handler<struct WGPUDawnDrmFormatProperties>()}, 
     {"struct WGPUDawnEncoderInternalUsageDescriptor", get_record_handler<struct WGPUDawnEncoderInternalUsageDescriptor>()}, 
     {"struct WGPUDawnFakeBufferOOMForTesting", get_record_handler<struct WGPUDawnFakeBufferOOMForTesting>()}, 
     {"struct WGPUDawnFakeDeviceInitializeErrorForTesting", get_record_handler<struct WGPUDawnFakeDeviceInitializeErrorForTesting>()}, 
     {"struct WGPUDawnFormatCapabilities", get_record_handler<struct WGPUDawnFormatCapabilities>()}, 
     {"struct WGPUDawnHostMappedPointerLimits", get_record_handler<struct WGPUDawnHostMappedPointerLimits>()}, 
     {"struct WGPUDawnInjectedInvalidSType", get_record_handler<struct WGPUDawnInjectedInvalidSType>()}, 
     {"struct WGPUDawnRenderPassColorAttachmentRenderToSingleSampled", get_record_handler<struct WGPUDawnRenderPassColorAttachmentRenderToSingleSampled>()}, 
     {"struct WGPUDawnShaderModuleSPIRVOptionsDescriptor", get_record_handler<struct WGPUDawnShaderModuleSPIRVOptionsDescriptor>()}, 
     {"struct WGPUDawnTexelCopyBufferRowAlignmentLimits", get_record_handler<struct WGPUDawnTexelCopyBufferRowAlignmentLimits>()}, 
     {"struct WGPUDawnTextureInternalUsageDescriptor", get_record_handler<struct WGPUDawnTextureInternalUsageDescriptor>()}, 
     {"struct WGPUDawnTogglesDescriptor", get_record_handler<struct WGPUDawnTogglesDescriptor>()}, 
     {"struct WGPUDawnWGSLBlocklist", get_record_handler<struct WGPUDawnWGSLBlocklist>()}, 
     {"struct WGPUDawnWireWGSLControl", get_record_handler<struct WGPUDawnWireWGSLControl>()}, 
     {"struct WGPUDepthStencilState", get_record_handler<struct WGPUDepthStencilState>()}, 
     {"struct WGPUDeviceDescriptor", get_record_handler<struct WGPUDeviceDescriptor>()}, 
     {"struct WGPUDeviceImpl", get_record_handler<struct WGPUDeviceImpl>()}, 
     {"struct WGPUDeviceLostCallbackInfo", get_record_handler<struct WGPUDeviceLostCallbackInfo>()}, 
     {"struct WGPUEmscriptenSurfaceSourceCanvasHTMLSelector", get_record_handler<struct WGPUEmscriptenSurfaceSourceCanvasHTMLSelector>()}, 
     {"struct WGPUExtent2D", get_record_handler<struct WGPUExtent2D>()}, 
     {"struct WGPUExtent3D", get_record_handler<struct WGPUExtent3D>()}, 
     {"struct WGPUExternalTextureBindingEntry", get_record_handler<struct WGPUExternalTextureBindingEntry>()}, 
     {"struct WGPUExternalTextureBindingLayout", get_record_handler<struct WGPUExternalTextureBindingLayout>()}, 
     {"struct WGPUExternalTextureDescriptor", get_record_handler<struct WGPUExternalTextureDescriptor>()}, 
     {"struct WGPUExternalTextureImpl", get_record_handler<struct WGPUExternalTextureImpl>()}, 
     {"struct WGPUFragmentState", get_record_handler<struct WGPUFragmentState>()}, 
     {"struct WGPUFuture", get_record_handler<struct WGPUFuture>()}, 
     {"struct WGPUFutureWaitInfo", get_record_handler<struct WGPUFutureWaitInfo>()}, 
     {"struct WGPUINTERNAL_HAVE_EMDAWNWEBGPU_HEADER", get_record_handler<struct WGPUINTERNAL_HAVE_EMDAWNWEBGPU_HEADER>()}, 
     {"struct WGPUImageCopyExternalTexture", get_record_handler<struct WGPUImageCopyExternalTexture>()}, 
     {"struct WGPUInstanceCapabilities", get_record_handler<struct WGPUInstanceCapabilities>()}, 
     {"struct WGPUInstanceDescriptor", get_record_handler<struct WGPUInstanceDescriptor>()}, 
     {"struct WGPUInstanceImpl", get_record_handler<struct WGPUInstanceImpl>()}, 
     {"struct WGPULimits", get_record_handler<struct WGPULimits>()}, 
     {"struct WGPULoggingCallbackInfo", get_record_handler<struct WGPULoggingCallbackInfo>()}, 
     {"struct WGPUMemoryHeapInfo", get_record_handler<struct WGPUMemoryHeapInfo>()}, 
     {"struct WGPUMultisampleState", get_record_handler<struct WGPUMultisampleState>()}, 
     {"struct WGPUOrigin2D", get_record_handler<struct WGPUOrigin2D>()}, 
     {"struct WGPUOrigin3D", get_record_handler<struct WGPUOrigin3D>()}, 
     {"struct WGPUPassTimestampWrites", get_record_handler<struct WGPUPassTimestampWrites>()}, 
     {"struct WGPUPipelineLayoutDescriptor", get_record_handler<struct WGPUPipelineLayoutDescriptor>()}, 
     {"struct WGPUPipelineLayoutImpl", get_record_handler<struct WGPUPipelineLayoutImpl>()}, 
     {"struct WGPUPipelineLayoutPixelLocalStorage", get_record_handler<struct WGPUPipelineLayoutPixelLocalStorage>()}, 
     {"struct WGPUPipelineLayoutStorageAttachment", get_record_handler<struct WGPUPipelineLayoutStorageAttachment>()}, 
     {"struct WGPUPopErrorScopeCallbackInfo", get_record_handler<struct WGPUPopErrorScopeCallbackInfo>()}, 
     {"struct WGPUPrimitiveState", get_record_handler<struct WGPUPrimitiveState>()}, 
     {"struct WGPUQuerySetDescriptor", get_record_handler<struct WGPUQuerySetDescriptor>()}, 
     {"struct WGPUQuerySetImpl", get_record_handler<struct WGPUQuerySetImpl>()}, 
     {"struct WGPUQueueDescriptor", get_record_handler<struct WGPUQueueDescriptor>()}, 
     {"struct WGPUQueueImpl", get_record_handler<struct WGPUQueueImpl>()}, 
     {"struct WGPUQueueWorkDoneCallbackInfo", get_record_handler<struct WGPUQueueWorkDoneCallbackInfo>()}, 
     {"struct WGPURenderBundleDescriptor", get_record_handler<struct WGPURenderBundleDescriptor>()}, 
     {"struct WGPURenderBundleEncoderDescriptor", get_record_handler<struct WGPURenderBundleEncoderDescriptor>()}, 
     {"struct WGPURenderBundleEncoderImpl", get_record_handler<struct WGPURenderBundleEncoderImpl>()}, 
     {"struct WGPURenderBundleImpl", get_record_handler<struct WGPURenderBundleImpl>()}, 
     {"struct WGPURenderPassColorAttachment", get_record_handler<struct WGPURenderPassColorAttachment>()}, 
     {"struct WGPURenderPassDepthStencilAttachment", get_record_handler<struct WGPURenderPassDepthStencilAttachment>()}, 
     {"struct WGPURenderPassDescriptor", get_record_handler<struct WGPURenderPassDescriptor>()}, 
     {"struct WGPURenderPassDescriptorExpandResolveRect", get_record_handler<struct WGPURenderPassDescriptorExpandResolveRect>()}, 
     {"struct WGPURenderPassDescriptorResolveRect", get_record_handler<struct WGPURenderPassDescriptorResolveRect>()}, 
     {"struct WGPURenderPassEncoderImpl", get_record_handler<struct WGPURenderPassEncoderImpl>()}, 
     {"struct WGPURenderPassMaxDrawCount", get_record_handler<struct WGPURenderPassMaxDrawCount>()}, 
     {"struct WGPURenderPassPixelLocalStorage", get_record_handler<struct WGPURenderPassPixelLocalStorage>()}, 
     {"struct WGPURenderPassStorageAttachment", get_record_handler<struct WGPURenderPassStorageAttachment>()}, 
     {"struct WGPURenderPipelineDescriptor", get_record_handler<struct WGPURenderPipelineDescriptor>()}, 
     {"struct WGPURenderPipelineImpl", get_record_handler<struct WGPURenderPipelineImpl>()}, 
     {"struct WGPURequestAdapterCallbackInfo", get_record_handler<struct WGPURequestAdapterCallbackInfo>()}, 
     {"struct WGPURequestAdapterOptions", get_record_handler<struct WGPURequestAdapterOptions>()}, 
     {"struct WGPURequestAdapterWebGPUBackendOptions", get_record_handler<struct WGPURequestAdapterWebGPUBackendOptions>()}, 
     {"struct WGPURequestAdapterWebXROptions", get_record_handler<struct WGPURequestAdapterWebXROptions>()}, 
     {"struct WGPURequestDeviceCallbackInfo", get_record_handler<struct WGPURequestDeviceCallbackInfo>()}, 
     {"struct WGPUSamplerBindingLayout", get_record_handler<struct WGPUSamplerBindingLayout>()}, 
     {"struct WGPUSamplerDescriptor", get_record_handler<struct WGPUSamplerDescriptor>()}, 
     {"struct WGPUSamplerImpl", get_record_handler<struct WGPUSamplerImpl>()}, 
     {"struct WGPUShaderModuleCompilationOptions", get_record_handler<struct WGPUShaderModuleCompilationOptions>()}, 
     {"struct WGPUShaderModuleDescriptor", get_record_handler<struct WGPUShaderModuleDescriptor>()}, 
     {"struct WGPUShaderModuleImpl", get_record_handler<struct WGPUShaderModuleImpl>()}, 
     {"struct WGPUShaderSourceSPIRV", get_record_handler<struct WGPUShaderSourceSPIRV>()}, 
     {"struct WGPUShaderSourceWGSL", get_record_handler<struct WGPUShaderSourceWGSL>()}, 
     {"struct WGPUSharedBufferMemoryBeginAccessDescriptor", get_record_handler<struct WGPUSharedBufferMemoryBeginAccessDescriptor>()}, 
     {"struct WGPUSharedBufferMemoryDescriptor", get_record_handler<struct WGPUSharedBufferMemoryDescriptor>()}, 
     {"struct WGPUSharedBufferMemoryEndAccessState", get_record_handler<struct WGPUSharedBufferMemoryEndAccessState>()}, 
     {"struct WGPUSharedBufferMemoryImpl", get_record_handler<struct WGPUSharedBufferMemoryImpl>()}, 
     {"struct WGPUSharedBufferMemoryProperties", get_record_handler<struct WGPUSharedBufferMemoryProperties>()}, 
     {"struct WGPUSharedFenceDXGISharedHandleDescriptor", get_record_handler<struct WGPUSharedFenceDXGISharedHandleDescriptor>()}, 
     {"struct WGPUSharedFenceDXGISharedHandleExportInfo", get_record_handler<struct WGPUSharedFenceDXGISharedHandleExportInfo>()}, 
     {"struct WGPUSharedFenceDescriptor", get_record_handler<struct WGPUSharedFenceDescriptor>()}, 
     {"struct WGPUSharedFenceEGLSyncDescriptor", get_record_handler<struct WGPUSharedFenceEGLSyncDescriptor>()}, 
     {"struct WGPUSharedFenceEGLSyncExportInfo", get_record_handler<struct WGPUSharedFenceEGLSyncExportInfo>()}, 
     {"struct WGPUSharedFenceExportInfo", get_record_handler<struct WGPUSharedFenceExportInfo>()}, 
     {"struct WGPUSharedFenceImpl", get_record_handler<struct WGPUSharedFenceImpl>()}, 
     {"struct WGPUSharedFenceMTLSharedEventDescriptor", get_record_handler<struct WGPUSharedFenceMTLSharedEventDescriptor>()}, 
     {"struct WGPUSharedFenceMTLSharedEventExportInfo", get_record_handler<struct WGPUSharedFenceMTLSharedEventExportInfo>()}, 
     {"struct WGPUSharedFenceSyncFDDescriptor", get_record_handler<struct WGPUSharedFenceSyncFDDescriptor>()}, 
     {"struct WGPUSharedFenceSyncFDExportInfo", get_record_handler<struct WGPUSharedFenceSyncFDExportInfo>()}, 
     {"struct WGPUSharedFenceVkSemaphoreOpaqueFDDescriptor", get_record_handler<struct WGPUSharedFenceVkSemaphoreOpaqueFDDescriptor>()}, 
     {"struct WGPUSharedFenceVkSemaphoreOpaqueFDExportInfo", get_record_handler<struct WGPUSharedFenceVkSemaphoreOpaqueFDExportInfo>()}, 
     {"struct WGPUSharedFenceVkSemaphoreZirconHandleDescriptor", get_record_handler<struct WGPUSharedFenceVkSemaphoreZirconHandleDescriptor>()}, 
     {"struct WGPUSharedFenceVkSemaphoreZirconHandleExportInfo", get_record_handler<struct WGPUSharedFenceVkSemaphoreZirconHandleExportInfo>()}, 
     {"struct WGPUSharedTextureMemoryAHardwareBufferDescriptor", get_record_handler<struct WGPUSharedTextureMemoryAHardwareBufferDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryAHardwareBufferProperties", get_record_handler<struct WGPUSharedTextureMemoryAHardwareBufferProperties>()}, 
     {"struct WGPUSharedTextureMemoryBeginAccessDescriptor", get_record_handler<struct WGPUSharedTextureMemoryBeginAccessDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryD3DSwapchainBeginState", get_record_handler<struct WGPUSharedTextureMemoryD3DSwapchainBeginState>()}, 
     {"struct WGPUSharedTextureMemoryDXGISharedHandleDescriptor", get_record_handler<struct WGPUSharedTextureMemoryDXGISharedHandleDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryDescriptor", get_record_handler<struct WGPUSharedTextureMemoryDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryDmaBufDescriptor", get_record_handler<struct WGPUSharedTextureMemoryDmaBufDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryDmaBufPlane", get_record_handler<struct WGPUSharedTextureMemoryDmaBufPlane>()}, 
     {"struct WGPUSharedTextureMemoryEGLImageDescriptor", get_record_handler<struct WGPUSharedTextureMemoryEGLImageDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryEndAccessState", get_record_handler<struct WGPUSharedTextureMemoryEndAccessState>()}, 
     {"struct WGPUSharedTextureMemoryIOSurfaceDescriptor", get_record_handler<struct WGPUSharedTextureMemoryIOSurfaceDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryImpl", get_record_handler<struct WGPUSharedTextureMemoryImpl>()}, 
     {"struct WGPUSharedTextureMemoryOpaqueFDDescriptor", get_record_handler<struct WGPUSharedTextureMemoryOpaqueFDDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryProperties", get_record_handler<struct WGPUSharedTextureMemoryProperties>()}, 
     {"struct WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor", get_record_handler<struct WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor>()}, 
     {"struct WGPUSharedTextureMemoryVkImageLayoutBeginState", get_record_handler<struct WGPUSharedTextureMemoryVkImageLayoutBeginState>()}, 
     {"struct WGPUSharedTextureMemoryVkImageLayoutEndState", get_record_handler<struct WGPUSharedTextureMemoryVkImageLayoutEndState>()}, 
     {"struct WGPUSharedTextureMemoryZirconHandleDescriptor", get_record_handler<struct WGPUSharedTextureMemoryZirconHandleDescriptor>()}, 
     {"struct WGPUStaticSamplerBindingLayout", get_record_handler<struct WGPUStaticSamplerBindingLayout>()}, 
     {"struct WGPUStencilFaceState", get_record_handler<struct WGPUStencilFaceState>()}, 
     {"struct WGPUStorageTextureBindingLayout", get_record_handler<struct WGPUStorageTextureBindingLayout>()}, 
     {"struct WGPUStringView", get_record_handler<struct WGPUStringView>()}, 
     {"struct WGPUSubgroupMatrixConfig", get_record_handler<struct WGPUSubgroupMatrixConfig>()}, 
     {"struct WGPUSupportedFeatures", get_record_handler<struct WGPUSupportedFeatures>()}, 
     {"struct WGPUSupportedWGSLLanguageFeatures", get_record_handler<struct WGPUSupportedWGSLLanguageFeatures>()}, 
     {"struct WGPUSurfaceCapabilities", get_record_handler<struct WGPUSurfaceCapabilities>()}, 
     {"struct WGPUSurfaceColorManagement", get_record_handler<struct WGPUSurfaceColorManagement>()}, 
     {"struct WGPUSurfaceConfiguration", get_record_handler<struct WGPUSurfaceConfiguration>()}, 
     {"struct WGPUSurfaceDescriptor", get_record_handler<struct WGPUSurfaceDescriptor>()}, 
     {"struct WGPUSurfaceDescriptorFromWindowsCoreWindow", get_record_handler<struct WGPUSurfaceDescriptorFromWindowsCoreWindow>()}, 
     {"struct WGPUSurfaceDescriptorFromWindowsUWPSwapChainPanel", get_record_handler<struct WGPUSurfaceDescriptorFromWindowsUWPSwapChainPanel>()}, 
     {"struct WGPUSurfaceDescriptorFromWindowsWinUISwapChainPanel", get_record_handler<struct WGPUSurfaceDescriptorFromWindowsWinUISwapChainPanel>()}, 
     {"struct WGPUSurfaceImpl", get_record_handler<struct WGPUSurfaceImpl>()}, 
     {"struct WGPUSurfaceSourceAndroidNativeWindow", get_record_handler<struct WGPUSurfaceSourceAndroidNativeWindow>()}, 
     {"struct WGPUSurfaceSourceMetalLayer", get_record_handler<struct WGPUSurfaceSourceMetalLayer>()}, 
     {"struct WGPUSurfaceSourceWaylandSurface", get_record_handler<struct WGPUSurfaceSourceWaylandSurface>()}, 
     {"struct WGPUSurfaceSourceWindowsHWND", get_record_handler<struct WGPUSurfaceSourceWindowsHWND>()}, 
     {"struct WGPUSurfaceSourceXCBWindow", get_record_handler<struct WGPUSurfaceSourceXCBWindow>()}, 
     {"struct WGPUSurfaceSourceXlibWindow", get_record_handler<struct WGPUSurfaceSourceXlibWindow>()}, 
     {"struct WGPUSurfaceTexture", get_record_handler<struct WGPUSurfaceTexture>()}, 
     {"struct WGPUTexelCopyBufferInfo", get_record_handler<struct WGPUTexelCopyBufferInfo>()}, 
     {"struct WGPUTexelCopyBufferLayout", get_record_handler<struct WGPUTexelCopyBufferLayout>()}, 
     {"struct WGPUTexelCopyTextureInfo", get_record_handler<struct WGPUTexelCopyTextureInfo>()}, 
     {"struct WGPUTextureBindingLayout", get_record_handler<struct WGPUTextureBindingLayout>()}, 
     {"struct WGPUTextureBindingViewDimensionDescriptor", get_record_handler<struct WGPUTextureBindingViewDimensionDescriptor>()}, 
     {"struct WGPUTextureDescriptor", get_record_handler<struct WGPUTextureDescriptor>()}, 
     {"struct WGPUTextureImpl", get_record_handler<struct WGPUTextureImpl>()}, 
     {"struct WGPUTextureViewDescriptor", get_record_handler<struct WGPUTextureViewDescriptor>()}, 
     {"struct WGPUTextureViewImpl", get_record_handler<struct WGPUTextureViewImpl>()}, 
     {"struct WGPUUncapturedErrorCallbackInfo", get_record_handler<struct WGPUUncapturedErrorCallbackInfo>()}, 
     {"struct WGPUVertexAttribute", get_record_handler<struct WGPUVertexAttribute>()}, 
     {"struct WGPUVertexBufferLayout", get_record_handler<struct WGPUVertexBufferLayout>()}, 
     {"struct WGPUVertexState", get_record_handler<struct WGPUVertexState>()}, 
     {"struct WGPUYCbCrVkDescriptor", get_record_handler<struct WGPUYCbCrVkDescriptor>()}
}};
constexpr std::array<std::pair<const char*, RecordHandler>, 548> typedefs = {{
     {"WGPUAHardwareBufferProperties", get_typedef_handler<WGPUAHardwareBufferProperties>()}, 
     {"WGPUAdapter", get_typedef_handler<WGPUAdapter>()}, 
     {"WGPUAdapterInfo", get_typedef_handler<WGPUAdapterInfo>()}, 
     {"WGPUAdapterPropertiesD3D", get_typedef_handler<WGPUAdapterPropertiesD3D>()}, 
     {"WGPUAdapterPropertiesMemoryHeaps", get_typedef_handler<WGPUAdapterPropertiesMemoryHeaps>()}, 
     {"WGPUAdapterPropertiesSubgroupMatrixConfigs", get_typedef_handler<WGPUAdapterPropertiesSubgroupMatrixConfigs>()}, 
     {"WGPUAdapterPropertiesVk", get_typedef_handler<WGPUAdapterPropertiesVk>()}, 
     {"WGPUAdapterType", get_typedef_handler<WGPUAdapterType>()}, 
     {"WGPUAddressMode", get_typedef_handler<WGPUAddressMode>()}, 
     {"WGPUAlphaMode", get_typedef_handler<WGPUAlphaMode>()}, 
     {"WGPUBackendType", get_typedef_handler<WGPUBackendType>()}, 
     {"WGPUBindGroup", get_typedef_handler<WGPUBindGroup>()}, 
     {"WGPUBindGroupDescriptor", get_typedef_handler<WGPUBindGroupDescriptor>()}, 
     {"WGPUBindGroupEntry", get_typedef_handler<WGPUBindGroupEntry>()}, 
     {"WGPUBindGroupLayout", get_typedef_handler<WGPUBindGroupLayout>()}, 
     {"WGPUBindGroupLayoutDescriptor", get_typedef_handler<WGPUBindGroupLayoutDescriptor>()}, 
     {"WGPUBindGroupLayoutEntry", get_typedef_handler<WGPUBindGroupLayoutEntry>()}, 
     {"WGPUBlendComponent", get_typedef_handler<WGPUBlendComponent>()}, 
     {"WGPUBlendFactor", get_typedef_handler<WGPUBlendFactor>()}, 
     {"WGPUBlendOperation", get_typedef_handler<WGPUBlendOperation>()}, 
     {"WGPUBlendState", get_typedef_handler<WGPUBlendState>()}, 
     {"WGPUBool", get_typedef_handler<WGPUBool>()}, 
     {"WGPUBuffer", get_typedef_handler<WGPUBuffer>()}, 
     {"WGPUBufferBindingLayout", get_typedef_handler<WGPUBufferBindingLayout>()}, 
     {"WGPUBufferBindingType", get_typedef_handler<WGPUBufferBindingType>()}, 
     {"WGPUBufferDescriptor", get_typedef_handler<WGPUBufferDescriptor>()}, 
     {"WGPUBufferHostMappedPointer", get_typedef_handler<WGPUBufferHostMappedPointer>()}, 
     {"WGPUBufferMapCallback", get_typedef_handler<WGPUBufferMapCallback>()}, 
     {"WGPUBufferMapCallbackInfo", get_typedef_handler<WGPUBufferMapCallbackInfo>()}, 
     {"WGPUBufferMapState", get_typedef_handler<WGPUBufferMapState>()}, 
     {"WGPUBufferUsage", get_typedef_handler<WGPUBufferUsage>()}, 
     {"WGPUCallback", get_typedef_handler<WGPUCallback>()}, 
     {"WGPUCallbackMode", get_typedef_handler<WGPUCallbackMode>()}, 
     {"WGPUChainedStruct", get_typedef_handler<WGPUChainedStruct>()}, 
     {"WGPUColor", get_typedef_handler<WGPUColor>()}, 
     {"WGPUColorTargetState", get_typedef_handler<WGPUColorTargetState>()}, 
     {"WGPUColorTargetStateExpandResolveTextureDawn", get_typedef_handler<WGPUColorTargetStateExpandResolveTextureDawn>()}, 
     {"WGPUColorWriteMask", get_typedef_handler<WGPUColorWriteMask>()}, 
     {"WGPUCommandBuffer", get_typedef_handler<WGPUCommandBuffer>()}, 
     {"WGPUCommandBufferDescriptor", get_typedef_handler<WGPUCommandBufferDescriptor>()}, 
     {"WGPUCommandEncoder", get_typedef_handler<WGPUCommandEncoder>()}, 
     {"WGPUCommandEncoderDescriptor", get_typedef_handler<WGPUCommandEncoderDescriptor>()}, 
     {"WGPUCompareFunction", get_typedef_handler<WGPUCompareFunction>()}, 
     {"WGPUCompatibilityModeLimits", get_typedef_handler<WGPUCompatibilityModeLimits>()}, 
     {"WGPUCompilationInfo", get_typedef_handler<WGPUCompilationInfo>()}, 
     {"WGPUCompilationInfoCallback", get_typedef_handler<WGPUCompilationInfoCallback>()}, 
     {"WGPUCompilationInfoCallbackInfo", get_typedef_handler<WGPUCompilationInfoCallbackInfo>()}, 
     {"WGPUCompilationInfoRequestStatus", get_typedef_handler<WGPUCompilationInfoRequestStatus>()}, 
     {"WGPUCompilationMessage", get_typedef_handler<WGPUCompilationMessage>()}, 
     {"WGPUCompilationMessageType", get_typedef_handler<WGPUCompilationMessageType>()}, 
     {"WGPUCompositeAlphaMode", get_typedef_handler<WGPUCompositeAlphaMode>()}, 
     {"WGPUComputePassDescriptor", get_typedef_handler<WGPUComputePassDescriptor>()}, 
     {"WGPUComputePassEncoder", get_typedef_handler<WGPUComputePassEncoder>()}, 
     {"WGPUComputePipeline", get_typedef_handler<WGPUComputePipeline>()}, 
     {"WGPUComputePipelineDescriptor", get_typedef_handler<WGPUComputePipelineDescriptor>()}, 
     {"WGPUComputeState", get_typedef_handler<WGPUComputeState>()}, 
     {"WGPUConstantEntry", get_typedef_handler<WGPUConstantEntry>()}, 
     {"WGPUCopyTextureForBrowserOptions", get_typedef_handler<WGPUCopyTextureForBrowserOptions>()}, 
     {"WGPUCreateComputePipelineAsyncCallback", get_typedef_handler<WGPUCreateComputePipelineAsyncCallback>()}, 
     {"WGPUCreateComputePipelineAsyncCallbackInfo", get_typedef_handler<WGPUCreateComputePipelineAsyncCallbackInfo>()}, 
     {"WGPUCreatePipelineAsyncStatus", get_typedef_handler<WGPUCreatePipelineAsyncStatus>()}, 
     {"WGPUCreateRenderPipelineAsyncCallback", get_typedef_handler<WGPUCreateRenderPipelineAsyncCallback>()}, 
     {"WGPUCreateRenderPipelineAsyncCallbackInfo", get_typedef_handler<WGPUCreateRenderPipelineAsyncCallbackInfo>()}, 
     {"WGPUCullMode", get_typedef_handler<WGPUCullMode>()}, 
     {"WGPUDawnAdapterPropertiesPowerPreference", get_typedef_handler<WGPUDawnAdapterPropertiesPowerPreference>()}, 
     {"WGPUDawnBufferDescriptorErrorInfoFromWireClient", get_typedef_handler<WGPUDawnBufferDescriptorErrorInfoFromWireClient>()}, 
     {"WGPUDawnCacheDeviceDescriptor", get_typedef_handler<WGPUDawnCacheDeviceDescriptor>()}, 
     {"WGPUDawnCompilationMessageUtf16", get_typedef_handler<WGPUDawnCompilationMessageUtf16>()}, 
     {"WGPUDawnDeviceAllocatorControl", get_typedef_handler<WGPUDawnDeviceAllocatorControl>()}, 
     {"WGPUDawnDrmFormatCapabilities", get_typedef_handler<WGPUDawnDrmFormatCapabilities>()}, 
     {"WGPUDawnDrmFormatProperties", get_typedef_handler<WGPUDawnDrmFormatProperties>()}, 
     {"WGPUDawnEncoderInternalUsageDescriptor", get_typedef_handler<WGPUDawnEncoderInternalUsageDescriptor>()}, 
     {"WGPUDawnFakeBufferOOMForTesting", get_typedef_handler<WGPUDawnFakeBufferOOMForTesting>()}, 
     {"WGPUDawnFakeDeviceInitializeErrorForTesting", get_typedef_handler<WGPUDawnFakeDeviceInitializeErrorForTesting>()}, 
     {"WGPUDawnFormatCapabilities", get_typedef_handler<WGPUDawnFormatCapabilities>()}, 
     {"WGPUDawnHostMappedPointerLimits", get_typedef_handler<WGPUDawnHostMappedPointerLimits>()}, 
     {"WGPUDawnInjectedInvalidSType", get_typedef_handler<WGPUDawnInjectedInvalidSType>()}, 
     {"WGPUDawnLoadCacheDataFunction", get_typedef_handler<WGPUDawnLoadCacheDataFunction>()}, 
     {"WGPUDawnRenderPassColorAttachmentRenderToSingleSampled", get_typedef_handler<WGPUDawnRenderPassColorAttachmentRenderToSingleSampled>()}, 
     {"WGPUDawnShaderModuleSPIRVOptionsDescriptor", get_typedef_handler<WGPUDawnShaderModuleSPIRVOptionsDescriptor>()}, 
     {"WGPUDawnStoreCacheDataFunction", get_typedef_handler<WGPUDawnStoreCacheDataFunction>()}, 
     {"WGPUDawnTexelCopyBufferRowAlignmentLimits", get_typedef_handler<WGPUDawnTexelCopyBufferRowAlignmentLimits>()}, 
     {"WGPUDawnTextureInternalUsageDescriptor", get_typedef_handler<WGPUDawnTextureInternalUsageDescriptor>()}, 
     {"WGPUDawnTogglesDescriptor", get_typedef_handler<WGPUDawnTogglesDescriptor>()}, 
     {"WGPUDawnWGSLBlocklist", get_typedef_handler<WGPUDawnWGSLBlocklist>()}, 
     {"WGPUDawnWireWGSLControl", get_typedef_handler<WGPUDawnWireWGSLControl>()}, 
     {"WGPUDepthStencilState", get_typedef_handler<WGPUDepthStencilState>()}, 
     {"WGPUDevice", get_typedef_handler<WGPUDevice>()}, 
     {"WGPUDeviceDescriptor", get_typedef_handler<WGPUDeviceDescriptor>()}, 
     {"WGPUDeviceLostCallback", get_typedef_handler<WGPUDeviceLostCallback>()}, 
     {"WGPUDeviceLostCallbackInfo", get_typedef_handler<WGPUDeviceLostCallbackInfo>()}, 
     {"WGPUDeviceLostReason", get_typedef_handler<WGPUDeviceLostReason>()}, 
     {"WGPUEmscriptenSurfaceSourceCanvasHTMLSelector", get_typedef_handler<WGPUEmscriptenSurfaceSourceCanvasHTMLSelector>()}, 
     {"WGPUErrorFilter", get_typedef_handler<WGPUErrorFilter>()}, 
     {"WGPUErrorType", get_typedef_handler<WGPUErrorType>()}, 
     {"WGPUExtent2D", get_typedef_handler<WGPUExtent2D>()}, 
     {"WGPUExtent3D", get_typedef_handler<WGPUExtent3D>()}, 
     {"WGPUExternalTexture", get_typedef_handler<WGPUExternalTexture>()}, 
     {"WGPUExternalTextureBindingEntry", get_typedef_handler<WGPUExternalTextureBindingEntry>()}, 
     {"WGPUExternalTextureBindingLayout", get_typedef_handler<WGPUExternalTextureBindingLayout>()}, 
     {"WGPUExternalTextureDescriptor", get_typedef_handler<WGPUExternalTextureDescriptor>()}, 
     {"WGPUExternalTextureRotation", get_typedef_handler<WGPUExternalTextureRotation>()}, 
     {"WGPUFeatureLevel", get_typedef_handler<WGPUFeatureLevel>()}, 
     {"WGPUFeatureName", get_typedef_handler<WGPUFeatureName>()}, 
     {"WGPUFilterMode", get_typedef_handler<WGPUFilterMode>()}, 
     {"WGPUFlags", get_typedef_handler<WGPUFlags>()}, 
     {"WGPUFragmentState", get_typedef_handler<WGPUFragmentState>()}, 
     {"WGPUFrontFace", get_typedef_handler<WGPUFrontFace>()}, 
     {"WGPUFuture", get_typedef_handler<WGPUFuture>()}, 
     {"WGPUFutureWaitInfo", get_typedef_handler<WGPUFutureWaitInfo>()}, 
     {"WGPUHeapProperty", get_typedef_handler<WGPUHeapProperty>()}, 
     {"WGPUINTERNAL_HAVE_EMDAWNWEBGPU_HEADER", get_typedef_handler<WGPUINTERNAL_HAVE_EMDAWNWEBGPU_HEADER>()}, 
     {"WGPUImageCopyExternalTexture", get_typedef_handler<WGPUImageCopyExternalTexture>()}, 
     {"WGPUIndexFormat", get_typedef_handler<WGPUIndexFormat>()}, 
     {"WGPUInstance", get_typedef_handler<WGPUInstance>()}, 
     {"WGPUInstanceCapabilities", get_typedef_handler<WGPUInstanceCapabilities>()}, 
     {"WGPUInstanceDescriptor", get_typedef_handler<WGPUInstanceDescriptor>()}, 
     {"WGPULimits", get_typedef_handler<WGPULimits>()}, 
     {"WGPULoadOp", get_typedef_handler<WGPULoadOp>()}, 
     {"WGPULoggingCallback", get_typedef_handler<WGPULoggingCallback>()}, 
     {"WGPULoggingCallbackInfo", get_typedef_handler<WGPULoggingCallbackInfo>()}, 
     {"WGPULoggingType", get_typedef_handler<WGPULoggingType>()}, 
     {"WGPUMapAsyncStatus", get_typedef_handler<WGPUMapAsyncStatus>()}, 
     {"WGPUMapMode", get_typedef_handler<WGPUMapMode>()}, 
     {"WGPUMemoryHeapInfo", get_typedef_handler<WGPUMemoryHeapInfo>()}, 
     {"WGPUMipmapFilterMode", get_typedef_handler<WGPUMipmapFilterMode>()}, 
     {"WGPUMultisampleState", get_typedef_handler<WGPUMultisampleState>()}, 
     {"WGPUOptionalBool", get_typedef_handler<WGPUOptionalBool>()}, 
     {"WGPUOrigin2D", get_typedef_handler<WGPUOrigin2D>()}, 
     {"WGPUOrigin3D", get_typedef_handler<WGPUOrigin3D>()}, 
     {"WGPUPassTimestampWrites", get_typedef_handler<WGPUPassTimestampWrites>()}, 
     {"WGPUPipelineLayout", get_typedef_handler<WGPUPipelineLayout>()}, 
     {"WGPUPipelineLayoutDescriptor", get_typedef_handler<WGPUPipelineLayoutDescriptor>()}, 
     {"WGPUPipelineLayoutPixelLocalStorage", get_typedef_handler<WGPUPipelineLayoutPixelLocalStorage>()}, 
     {"WGPUPipelineLayoutStorageAttachment", get_typedef_handler<WGPUPipelineLayoutStorageAttachment>()}, 
     {"WGPUPopErrorScopeCallback", get_typedef_handler<WGPUPopErrorScopeCallback>()}, 
     {"WGPUPopErrorScopeCallbackInfo", get_typedef_handler<WGPUPopErrorScopeCallbackInfo>()}, 
     {"WGPUPopErrorScopeStatus", get_typedef_handler<WGPUPopErrorScopeStatus>()}, 
     {"WGPUPowerPreference", get_typedef_handler<WGPUPowerPreference>()}, 
     {"WGPUPredefinedColorSpace", get_typedef_handler<WGPUPredefinedColorSpace>()}, 
     {"WGPUPresentMode", get_typedef_handler<WGPUPresentMode>()}, 
     {"WGPUPrimitiveState", get_typedef_handler<WGPUPrimitiveState>()}, 
     {"WGPUPrimitiveTopology", get_typedef_handler<WGPUPrimitiveTopology>()}, 
     {"WGPUProc", get_typedef_handler<WGPUProc>()}, 
     {"WGPUProcAdapterAddRef", get_typedef_handler<WGPUProcAdapterAddRef>()}, 
     {"WGPUProcAdapterCreateDevice", get_typedef_handler<WGPUProcAdapterCreateDevice>()}, 
     {"WGPUProcAdapterGetFeatures", get_typedef_handler<WGPUProcAdapterGetFeatures>()}, 
     {"WGPUProcAdapterGetFormatCapabilities", get_typedef_handler<WGPUProcAdapterGetFormatCapabilities>()}, 
     {"WGPUProcAdapterGetInfo", get_typedef_handler<WGPUProcAdapterGetInfo>()}, 
     {"WGPUProcAdapterGetInstance", get_typedef_handler<WGPUProcAdapterGetInstance>()}, 
     {"WGPUProcAdapterGetLimits", get_typedef_handler<WGPUProcAdapterGetLimits>()}, 
     {"WGPUProcAdapterHasFeature", get_typedef_handler<WGPUProcAdapterHasFeature>()}, 
     {"WGPUProcAdapterInfoFreeMembers", get_typedef_handler<WGPUProcAdapterInfoFreeMembers>()}, 
     {"WGPUProcAdapterPropertiesMemoryHeapsFreeMembers", get_typedef_handler<WGPUProcAdapterPropertiesMemoryHeapsFreeMembers>()}, 
     {"WGPUProcAdapterPropertiesSubgroupMatrixConfigsFreeMembers", get_typedef_handler<WGPUProcAdapterPropertiesSubgroupMatrixConfigsFreeMembers>()}, 
     {"WGPUProcAdapterRelease", get_typedef_handler<WGPUProcAdapterRelease>()}, 
     {"WGPUProcAdapterRequestDevice", get_typedef_handler<WGPUProcAdapterRequestDevice>()}, 
     {"WGPUProcBindGroupAddRef", get_typedef_handler<WGPUProcBindGroupAddRef>()}, 
     {"WGPUProcBindGroupLayoutAddRef", get_typedef_handler<WGPUProcBindGroupLayoutAddRef>()}, 
     {"WGPUProcBindGroupLayoutRelease", get_typedef_handler<WGPUProcBindGroupLayoutRelease>()}, 
     {"WGPUProcBindGroupLayoutSetLabel", get_typedef_handler<WGPUProcBindGroupLayoutSetLabel>()}, 
     {"WGPUProcBindGroupRelease", get_typedef_handler<WGPUProcBindGroupRelease>()}, 
     {"WGPUProcBindGroupSetLabel", get_typedef_handler<WGPUProcBindGroupSetLabel>()}, 
     {"WGPUProcBufferAddRef", get_typedef_handler<WGPUProcBufferAddRef>()}, 
     {"WGPUProcBufferDestroy", get_typedef_handler<WGPUProcBufferDestroy>()}, 
     {"WGPUProcBufferGetConstMappedRange", get_typedef_handler<WGPUProcBufferGetConstMappedRange>()}, 
     {"WGPUProcBufferGetMapState", get_typedef_handler<WGPUProcBufferGetMapState>()}, 
     {"WGPUProcBufferGetMappedRange", get_typedef_handler<WGPUProcBufferGetMappedRange>()}, 
     {"WGPUProcBufferGetSize", get_typedef_handler<WGPUProcBufferGetSize>()}, 
     {"WGPUProcBufferGetUsage", get_typedef_handler<WGPUProcBufferGetUsage>()}, 
     {"WGPUProcBufferMapAsync", get_typedef_handler<WGPUProcBufferMapAsync>()}, 
     {"WGPUProcBufferReadMappedRange", get_typedef_handler<WGPUProcBufferReadMappedRange>()}, 
     {"WGPUProcBufferRelease", get_typedef_handler<WGPUProcBufferRelease>()}, 
     {"WGPUProcBufferSetLabel", get_typedef_handler<WGPUProcBufferSetLabel>()}, 
     {"WGPUProcBufferUnmap", get_typedef_handler<WGPUProcBufferUnmap>()}, 
     {"WGPUProcBufferWriteMappedRange", get_typedef_handler<WGPUProcBufferWriteMappedRange>()}, 
     {"WGPUProcCommandBufferAddRef", get_typedef_handler<WGPUProcCommandBufferAddRef>()}, 
     {"WGPUProcCommandBufferRelease", get_typedef_handler<WGPUProcCommandBufferRelease>()}, 
     {"WGPUProcCommandBufferSetLabel", get_typedef_handler<WGPUProcCommandBufferSetLabel>()}, 
     {"WGPUProcCommandEncoderAddRef", get_typedef_handler<WGPUProcCommandEncoderAddRef>()}, 
     {"WGPUProcCommandEncoderBeginComputePass", get_typedef_handler<WGPUProcCommandEncoderBeginComputePass>()}, 
     {"WGPUProcCommandEncoderBeginRenderPass", get_typedef_handler<WGPUProcCommandEncoderBeginRenderPass>()}, 
     {"WGPUProcCommandEncoderClearBuffer", get_typedef_handler<WGPUProcCommandEncoderClearBuffer>()}, 
     {"WGPUProcCommandEncoderCopyBufferToBuffer", get_typedef_handler<WGPUProcCommandEncoderCopyBufferToBuffer>()}, 
     {"WGPUProcCommandEncoderCopyBufferToTexture", get_typedef_handler<WGPUProcCommandEncoderCopyBufferToTexture>()}, 
     {"WGPUProcCommandEncoderCopyTextureToBuffer", get_typedef_handler<WGPUProcCommandEncoderCopyTextureToBuffer>()}, 
     {"WGPUProcCommandEncoderCopyTextureToTexture", get_typedef_handler<WGPUProcCommandEncoderCopyTextureToTexture>()}, 
     {"WGPUProcCommandEncoderFinish", get_typedef_handler<WGPUProcCommandEncoderFinish>()}, 
     {"WGPUProcCommandEncoderInjectValidationError", get_typedef_handler<WGPUProcCommandEncoderInjectValidationError>()}, 
     {"WGPUProcCommandEncoderInsertDebugMarker", get_typedef_handler<WGPUProcCommandEncoderInsertDebugMarker>()}, 
     {"WGPUProcCommandEncoderPopDebugGroup", get_typedef_handler<WGPUProcCommandEncoderPopDebugGroup>()}, 
     {"WGPUProcCommandEncoderPushDebugGroup", get_typedef_handler<WGPUProcCommandEncoderPushDebugGroup>()}, 
     {"WGPUProcCommandEncoderRelease", get_typedef_handler<WGPUProcCommandEncoderRelease>()}, 
     {"WGPUProcCommandEncoderResolveQuerySet", get_typedef_handler<WGPUProcCommandEncoderResolveQuerySet>()}, 
     {"WGPUProcCommandEncoderSetLabel", get_typedef_handler<WGPUProcCommandEncoderSetLabel>()}, 
     {"WGPUProcCommandEncoderWriteBuffer", get_typedef_handler<WGPUProcCommandEncoderWriteBuffer>()}, 
     {"WGPUProcCommandEncoderWriteTimestamp", get_typedef_handler<WGPUProcCommandEncoderWriteTimestamp>()}, 
     {"WGPUProcComputePassEncoderAddRef", get_typedef_handler<WGPUProcComputePassEncoderAddRef>()}, 
     {"WGPUProcComputePassEncoderDispatchWorkgroups", get_typedef_handler<WGPUProcComputePassEncoderDispatchWorkgroups>()}, 
     {"WGPUProcComputePassEncoderDispatchWorkgroupsIndirect", get_typedef_handler<WGPUProcComputePassEncoderDispatchWorkgroupsIndirect>()}, 
     {"WGPUProcComputePassEncoderEnd", get_typedef_handler<WGPUProcComputePassEncoderEnd>()}, 
     {"WGPUProcComputePassEncoderInsertDebugMarker", get_typedef_handler<WGPUProcComputePassEncoderInsertDebugMarker>()}, 
     {"WGPUProcComputePassEncoderPopDebugGroup", get_typedef_handler<WGPUProcComputePassEncoderPopDebugGroup>()}, 
     {"WGPUProcComputePassEncoderPushDebugGroup", get_typedef_handler<WGPUProcComputePassEncoderPushDebugGroup>()}, 
     {"WGPUProcComputePassEncoderRelease", get_typedef_handler<WGPUProcComputePassEncoderRelease>()}, 
     {"WGPUProcComputePassEncoderSetBindGroup", get_typedef_handler<WGPUProcComputePassEncoderSetBindGroup>()}, 
     {"WGPUProcComputePassEncoderSetImmediateData", get_typedef_handler<WGPUProcComputePassEncoderSetImmediateData>()}, 
     {"WGPUProcComputePassEncoderSetLabel", get_typedef_handler<WGPUProcComputePassEncoderSetLabel>()}, 
     {"WGPUProcComputePassEncoderSetPipeline", get_typedef_handler<WGPUProcComputePassEncoderSetPipeline>()}, 
     {"WGPUProcComputePassEncoderWriteTimestamp", get_typedef_handler<WGPUProcComputePassEncoderWriteTimestamp>()}, 
     {"WGPUProcComputePipelineAddRef", get_typedef_handler<WGPUProcComputePipelineAddRef>()}, 
     {"WGPUProcComputePipelineGetBindGroupLayout", get_typedef_handler<WGPUProcComputePipelineGetBindGroupLayout>()}, 
     {"WGPUProcComputePipelineRelease", get_typedef_handler<WGPUProcComputePipelineRelease>()}, 
     {"WGPUProcComputePipelineSetLabel", get_typedef_handler<WGPUProcComputePipelineSetLabel>()}, 
     {"WGPUProcCreateInstance", get_typedef_handler<WGPUProcCreateInstance>()}, 
     {"WGPUProcDawnDrmFormatCapabilitiesFreeMembers", get_typedef_handler<WGPUProcDawnDrmFormatCapabilitiesFreeMembers>()}, 
     {"WGPUProcDeviceAddRef", get_typedef_handler<WGPUProcDeviceAddRef>()}, 
     {"WGPUProcDeviceCreateBindGroup", get_typedef_handler<WGPUProcDeviceCreateBindGroup>()}, 
     {"WGPUProcDeviceCreateBindGroupLayout", get_typedef_handler<WGPUProcDeviceCreateBindGroupLayout>()}, 
     {"WGPUProcDeviceCreateBuffer", get_typedef_handler<WGPUProcDeviceCreateBuffer>()}, 
     {"WGPUProcDeviceCreateCommandEncoder", get_typedef_handler<WGPUProcDeviceCreateCommandEncoder>()}, 
     {"WGPUProcDeviceCreateComputePipeline", get_typedef_handler<WGPUProcDeviceCreateComputePipeline>()}, 
     {"WGPUProcDeviceCreateComputePipelineAsync", get_typedef_handler<WGPUProcDeviceCreateComputePipelineAsync>()}, 
     {"WGPUProcDeviceCreateErrorBuffer", get_typedef_handler<WGPUProcDeviceCreateErrorBuffer>()}, 
     {"WGPUProcDeviceCreateErrorExternalTexture", get_typedef_handler<WGPUProcDeviceCreateErrorExternalTexture>()}, 
     {"WGPUProcDeviceCreateErrorShaderModule", get_typedef_handler<WGPUProcDeviceCreateErrorShaderModule>()}, 
     {"WGPUProcDeviceCreateErrorTexture", get_typedef_handler<WGPUProcDeviceCreateErrorTexture>()}, 
     {"WGPUProcDeviceCreateExternalTexture", get_typedef_handler<WGPUProcDeviceCreateExternalTexture>()}, 
     {"WGPUProcDeviceCreatePipelineLayout", get_typedef_handler<WGPUProcDeviceCreatePipelineLayout>()}, 
     {"WGPUProcDeviceCreateQuerySet", get_typedef_handler<WGPUProcDeviceCreateQuerySet>()}, 
     {"WGPUProcDeviceCreateRenderBundleEncoder", get_typedef_handler<WGPUProcDeviceCreateRenderBundleEncoder>()}, 
     {"WGPUProcDeviceCreateRenderPipeline", get_typedef_handler<WGPUProcDeviceCreateRenderPipeline>()}, 
     {"WGPUProcDeviceCreateRenderPipelineAsync", get_typedef_handler<WGPUProcDeviceCreateRenderPipelineAsync>()}, 
     {"WGPUProcDeviceCreateSampler", get_typedef_handler<WGPUProcDeviceCreateSampler>()}, 
     {"WGPUProcDeviceCreateShaderModule", get_typedef_handler<WGPUProcDeviceCreateShaderModule>()}, 
     {"WGPUProcDeviceCreateTexture", get_typedef_handler<WGPUProcDeviceCreateTexture>()}, 
     {"WGPUProcDeviceDestroy", get_typedef_handler<WGPUProcDeviceDestroy>()}, 
     {"WGPUProcDeviceForceLoss", get_typedef_handler<WGPUProcDeviceForceLoss>()}, 
     {"WGPUProcDeviceGetAHardwareBufferProperties", get_typedef_handler<WGPUProcDeviceGetAHardwareBufferProperties>()}, 
     {"WGPUProcDeviceGetAdapter", get_typedef_handler<WGPUProcDeviceGetAdapter>()}, 
     {"WGPUProcDeviceGetAdapterInfo", get_typedef_handler<WGPUProcDeviceGetAdapterInfo>()}, 
     {"WGPUProcDeviceGetFeatures", get_typedef_handler<WGPUProcDeviceGetFeatures>()}, 
     {"WGPUProcDeviceGetLimits", get_typedef_handler<WGPUProcDeviceGetLimits>()}, 
     {"WGPUProcDeviceGetLostFuture", get_typedef_handler<WGPUProcDeviceGetLostFuture>()}, 
     {"WGPUProcDeviceGetQueue", get_typedef_handler<WGPUProcDeviceGetQueue>()}, 
     {"WGPUProcDeviceHasFeature", get_typedef_handler<WGPUProcDeviceHasFeature>()}, 
     {"WGPUProcDeviceImportSharedBufferMemory", get_typedef_handler<WGPUProcDeviceImportSharedBufferMemory>()}, 
     {"WGPUProcDeviceImportSharedFence", get_typedef_handler<WGPUProcDeviceImportSharedFence>()}, 
     {"WGPUProcDeviceImportSharedTextureMemory", get_typedef_handler<WGPUProcDeviceImportSharedTextureMemory>()}, 
     {"WGPUProcDeviceInjectError", get_typedef_handler<WGPUProcDeviceInjectError>()}, 
     {"WGPUProcDevicePopErrorScope", get_typedef_handler<WGPUProcDevicePopErrorScope>()}, 
     {"WGPUProcDevicePushErrorScope", get_typedef_handler<WGPUProcDevicePushErrorScope>()}, 
     {"WGPUProcDeviceRelease", get_typedef_handler<WGPUProcDeviceRelease>()}, 
     {"WGPUProcDeviceSetLabel", get_typedef_handler<WGPUProcDeviceSetLabel>()}, 
     {"WGPUProcDeviceSetLoggingCallback", get_typedef_handler<WGPUProcDeviceSetLoggingCallback>()}, 
     {"WGPUProcDeviceTick", get_typedef_handler<WGPUProcDeviceTick>()}, 
     {"WGPUProcDeviceValidateTextureDescriptor", get_typedef_handler<WGPUProcDeviceValidateTextureDescriptor>()}, 
     {"WGPUProcExternalTextureAddRef", get_typedef_handler<WGPUProcExternalTextureAddRef>()}, 
     {"WGPUProcExternalTextureDestroy", get_typedef_handler<WGPUProcExternalTextureDestroy>()}, 
     {"WGPUProcExternalTextureExpire", get_typedef_handler<WGPUProcExternalTextureExpire>()}, 
     {"WGPUProcExternalTextureRefresh", get_typedef_handler<WGPUProcExternalTextureRefresh>()}, 
     {"WGPUProcExternalTextureRelease", get_typedef_handler<WGPUProcExternalTextureRelease>()}, 
     {"WGPUProcExternalTextureSetLabel", get_typedef_handler<WGPUProcExternalTextureSetLabel>()}, 
     {"WGPUProcGetInstanceCapabilities", get_typedef_handler<WGPUProcGetInstanceCapabilities>()}, 
     {"WGPUProcGetProcAddress", get_typedef_handler<WGPUProcGetProcAddress>()}, 
     {"WGPUProcInstanceAddRef", get_typedef_handler<WGPUProcInstanceAddRef>()}, 
     {"WGPUProcInstanceCreateSurface", get_typedef_handler<WGPUProcInstanceCreateSurface>()}, 
     {"WGPUProcInstanceGetWGSLLanguageFeatures", get_typedef_handler<WGPUProcInstanceGetWGSLLanguageFeatures>()}, 
     {"WGPUProcInstanceHasWGSLLanguageFeature", get_typedef_handler<WGPUProcInstanceHasWGSLLanguageFeature>()}, 
     {"WGPUProcInstanceProcessEvents", get_typedef_handler<WGPUProcInstanceProcessEvents>()}, 
     {"WGPUProcInstanceRelease", get_typedef_handler<WGPUProcInstanceRelease>()}, 
     {"WGPUProcInstanceRequestAdapter", get_typedef_handler<WGPUProcInstanceRequestAdapter>()}, 
     {"WGPUProcInstanceWaitAny", get_typedef_handler<WGPUProcInstanceWaitAny>()}, 
     {"WGPUProcPipelineLayoutAddRef", get_typedef_handler<WGPUProcPipelineLayoutAddRef>()}, 
     {"WGPUProcPipelineLayoutRelease", get_typedef_handler<WGPUProcPipelineLayoutRelease>()}, 
     {"WGPUProcPipelineLayoutSetLabel", get_typedef_handler<WGPUProcPipelineLayoutSetLabel>()}, 
     {"WGPUProcQuerySetAddRef", get_typedef_handler<WGPUProcQuerySetAddRef>()}, 
     {"WGPUProcQuerySetDestroy", get_typedef_handler<WGPUProcQuerySetDestroy>()}, 
     {"WGPUProcQuerySetGetCount", get_typedef_handler<WGPUProcQuerySetGetCount>()}, 
     {"WGPUProcQuerySetGetType", get_typedef_handler<WGPUProcQuerySetGetType>()}, 
     {"WGPUProcQuerySetRelease", get_typedef_handler<WGPUProcQuerySetRelease>()}, 
     {"WGPUProcQuerySetSetLabel", get_typedef_handler<WGPUProcQuerySetSetLabel>()}, 
     {"WGPUProcQueueAddRef", get_typedef_handler<WGPUProcQueueAddRef>()}, 
     {"WGPUProcQueueCopyExternalTextureForBrowser", get_typedef_handler<WGPUProcQueueCopyExternalTextureForBrowser>()}, 
     {"WGPUProcQueueCopyTextureForBrowser", get_typedef_handler<WGPUProcQueueCopyTextureForBrowser>()}, 
     {"WGPUProcQueueOnSubmittedWorkDone", get_typedef_handler<WGPUProcQueueOnSubmittedWorkDone>()}, 
     {"WGPUProcQueueRelease", get_typedef_handler<WGPUProcQueueRelease>()}, 
     {"WGPUProcQueueSetLabel", get_typedef_handler<WGPUProcQueueSetLabel>()}, 
     {"WGPUProcQueueSubmit", get_typedef_handler<WGPUProcQueueSubmit>()}, 
     {"WGPUProcQueueWriteBuffer", get_typedef_handler<WGPUProcQueueWriteBuffer>()}, 
     {"WGPUProcQueueWriteTexture", get_typedef_handler<WGPUProcQueueWriteTexture>()}, 
     {"WGPUProcRenderBundleAddRef", get_typedef_handler<WGPUProcRenderBundleAddRef>()}, 
     {"WGPUProcRenderBundleEncoderAddRef", get_typedef_handler<WGPUProcRenderBundleEncoderAddRef>()}, 
     {"WGPUProcRenderBundleEncoderDraw", get_typedef_handler<WGPUProcRenderBundleEncoderDraw>()}, 
     {"WGPUProcRenderBundleEncoderDrawIndexed", get_typedef_handler<WGPUProcRenderBundleEncoderDrawIndexed>()}, 
     {"WGPUProcRenderBundleEncoderDrawIndexedIndirect", get_typedef_handler<WGPUProcRenderBundleEncoderDrawIndexedIndirect>()}, 
     {"WGPUProcRenderBundleEncoderDrawIndirect", get_typedef_handler<WGPUProcRenderBundleEncoderDrawIndirect>()}, 
     {"WGPUProcRenderBundleEncoderFinish", get_typedef_handler<WGPUProcRenderBundleEncoderFinish>()}, 
     {"WGPUProcRenderBundleEncoderInsertDebugMarker", get_typedef_handler<WGPUProcRenderBundleEncoderInsertDebugMarker>()}, 
     {"WGPUProcRenderBundleEncoderPopDebugGroup", get_typedef_handler<WGPUProcRenderBundleEncoderPopDebugGroup>()}, 
     {"WGPUProcRenderBundleEncoderPushDebugGroup", get_typedef_handler<WGPUProcRenderBundleEncoderPushDebugGroup>()}, 
     {"WGPUProcRenderBundleEncoderRelease", get_typedef_handler<WGPUProcRenderBundleEncoderRelease>()}, 
     {"WGPUProcRenderBundleEncoderSetBindGroup", get_typedef_handler<WGPUProcRenderBundleEncoderSetBindGroup>()}, 
     {"WGPUProcRenderBundleEncoderSetImmediateData", get_typedef_handler<WGPUProcRenderBundleEncoderSetImmediateData>()}, 
     {"WGPUProcRenderBundleEncoderSetIndexBuffer", get_typedef_handler<WGPUProcRenderBundleEncoderSetIndexBuffer>()}, 
     {"WGPUProcRenderBundleEncoderSetLabel", get_typedef_handler<WGPUProcRenderBundleEncoderSetLabel>()}, 
     {"WGPUProcRenderBundleEncoderSetPipeline", get_typedef_handler<WGPUProcRenderBundleEncoderSetPipeline>()}, 
     {"WGPUProcRenderBundleEncoderSetVertexBuffer", get_typedef_handler<WGPUProcRenderBundleEncoderSetVertexBuffer>()}, 
     {"WGPUProcRenderBundleRelease", get_typedef_handler<WGPUProcRenderBundleRelease>()}, 
     {"WGPUProcRenderBundleSetLabel", get_typedef_handler<WGPUProcRenderBundleSetLabel>()}, 
     {"WGPUProcRenderPassEncoderAddRef", get_typedef_handler<WGPUProcRenderPassEncoderAddRef>()}, 
     {"WGPUProcRenderPassEncoderBeginOcclusionQuery", get_typedef_handler<WGPUProcRenderPassEncoderBeginOcclusionQuery>()}, 
     {"WGPUProcRenderPassEncoderDraw", get_typedef_handler<WGPUProcRenderPassEncoderDraw>()}, 
     {"WGPUProcRenderPassEncoderDrawIndexed", get_typedef_handler<WGPUProcRenderPassEncoderDrawIndexed>()}, 
     {"WGPUProcRenderPassEncoderDrawIndexedIndirect", get_typedef_handler<WGPUProcRenderPassEncoderDrawIndexedIndirect>()}, 
     {"WGPUProcRenderPassEncoderDrawIndirect", get_typedef_handler<WGPUProcRenderPassEncoderDrawIndirect>()}, 
     {"WGPUProcRenderPassEncoderEnd", get_typedef_handler<WGPUProcRenderPassEncoderEnd>()}, 
     {"WGPUProcRenderPassEncoderEndOcclusionQuery", get_typedef_handler<WGPUProcRenderPassEncoderEndOcclusionQuery>()}, 
     {"WGPUProcRenderPassEncoderExecuteBundles", get_typedef_handler<WGPUProcRenderPassEncoderExecuteBundles>()}, 
     {"WGPUProcRenderPassEncoderInsertDebugMarker", get_typedef_handler<WGPUProcRenderPassEncoderInsertDebugMarker>()}, 
     {"WGPUProcRenderPassEncoderMultiDrawIndexedIndirect", get_typedef_handler<WGPUProcRenderPassEncoderMultiDrawIndexedIndirect>()}, 
     {"WGPUProcRenderPassEncoderMultiDrawIndirect", get_typedef_handler<WGPUProcRenderPassEncoderMultiDrawIndirect>()}, 
     {"WGPUProcRenderPassEncoderPixelLocalStorageBarrier", get_typedef_handler<WGPUProcRenderPassEncoderPixelLocalStorageBarrier>()}, 
     {"WGPUProcRenderPassEncoderPopDebugGroup", get_typedef_handler<WGPUProcRenderPassEncoderPopDebugGroup>()}, 
     {"WGPUProcRenderPassEncoderPushDebugGroup", get_typedef_handler<WGPUProcRenderPassEncoderPushDebugGroup>()}, 
     {"WGPUProcRenderPassEncoderRelease", get_typedef_handler<WGPUProcRenderPassEncoderRelease>()}, 
     {"WGPUProcRenderPassEncoderSetBindGroup", get_typedef_handler<WGPUProcRenderPassEncoderSetBindGroup>()}, 
     {"WGPUProcRenderPassEncoderSetBlendConstant", get_typedef_handler<WGPUProcRenderPassEncoderSetBlendConstant>()}, 
     {"WGPUProcRenderPassEncoderSetImmediateData", get_typedef_handler<WGPUProcRenderPassEncoderSetImmediateData>()}, 
     {"WGPUProcRenderPassEncoderSetIndexBuffer", get_typedef_handler<WGPUProcRenderPassEncoderSetIndexBuffer>()}, 
     {"WGPUProcRenderPassEncoderSetLabel", get_typedef_handler<WGPUProcRenderPassEncoderSetLabel>()}, 
     {"WGPUProcRenderPassEncoderSetPipeline", get_typedef_handler<WGPUProcRenderPassEncoderSetPipeline>()}, 
     {"WGPUProcRenderPassEncoderSetScissorRect", get_typedef_handler<WGPUProcRenderPassEncoderSetScissorRect>()}, 
     {"WGPUProcRenderPassEncoderSetStencilReference", get_typedef_handler<WGPUProcRenderPassEncoderSetStencilReference>()}, 
     {"WGPUProcRenderPassEncoderSetVertexBuffer", get_typedef_handler<WGPUProcRenderPassEncoderSetVertexBuffer>()}, 
     {"WGPUProcRenderPassEncoderSetViewport", get_typedef_handler<WGPUProcRenderPassEncoderSetViewport>()}, 
     {"WGPUProcRenderPassEncoderWriteTimestamp", get_typedef_handler<WGPUProcRenderPassEncoderWriteTimestamp>()}, 
     {"WGPUProcRenderPipelineAddRef", get_typedef_handler<WGPUProcRenderPipelineAddRef>()}, 
     {"WGPUProcRenderPipelineGetBindGroupLayout", get_typedef_handler<WGPUProcRenderPipelineGetBindGroupLayout>()}, 
     {"WGPUProcRenderPipelineRelease", get_typedef_handler<WGPUProcRenderPipelineRelease>()}, 
     {"WGPUProcRenderPipelineSetLabel", get_typedef_handler<WGPUProcRenderPipelineSetLabel>()}, 
     {"WGPUProcSamplerAddRef", get_typedef_handler<WGPUProcSamplerAddRef>()}, 
     {"WGPUProcSamplerRelease", get_typedef_handler<WGPUProcSamplerRelease>()}, 
     {"WGPUProcSamplerSetLabel", get_typedef_handler<WGPUProcSamplerSetLabel>()}, 
     {"WGPUProcShaderModuleAddRef", get_typedef_handler<WGPUProcShaderModuleAddRef>()}, 
     {"WGPUProcShaderModuleGetCompilationInfo", get_typedef_handler<WGPUProcShaderModuleGetCompilationInfo>()}, 
     {"WGPUProcShaderModuleRelease", get_typedef_handler<WGPUProcShaderModuleRelease>()}, 
     {"WGPUProcShaderModuleSetLabel", get_typedef_handler<WGPUProcShaderModuleSetLabel>()}, 
     {"WGPUProcSharedBufferMemoryAddRef", get_typedef_handler<WGPUProcSharedBufferMemoryAddRef>()}, 
     {"WGPUProcSharedBufferMemoryBeginAccess", get_typedef_handler<WGPUProcSharedBufferMemoryBeginAccess>()}, 
     {"WGPUProcSharedBufferMemoryCreateBuffer", get_typedef_handler<WGPUProcSharedBufferMemoryCreateBuffer>()}, 
     {"WGPUProcSharedBufferMemoryEndAccess", get_typedef_handler<WGPUProcSharedBufferMemoryEndAccess>()}, 
     {"WGPUProcSharedBufferMemoryEndAccessStateFreeMembers", get_typedef_handler<WGPUProcSharedBufferMemoryEndAccessStateFreeMembers>()}, 
     {"WGPUProcSharedBufferMemoryGetProperties", get_typedef_handler<WGPUProcSharedBufferMemoryGetProperties>()}, 
     {"WGPUProcSharedBufferMemoryIsDeviceLost", get_typedef_handler<WGPUProcSharedBufferMemoryIsDeviceLost>()}, 
     {"WGPUProcSharedBufferMemoryRelease", get_typedef_handler<WGPUProcSharedBufferMemoryRelease>()}, 
     {"WGPUProcSharedBufferMemorySetLabel", get_typedef_handler<WGPUProcSharedBufferMemorySetLabel>()}, 
     {"WGPUProcSharedFenceAddRef", get_typedef_handler<WGPUProcSharedFenceAddRef>()}, 
     {"WGPUProcSharedFenceExportInfo", get_typedef_handler<WGPUProcSharedFenceExportInfo>()}, 
     {"WGPUProcSharedFenceRelease", get_typedef_handler<WGPUProcSharedFenceRelease>()}, 
     {"WGPUProcSharedTextureMemoryAddRef", get_typedef_handler<WGPUProcSharedTextureMemoryAddRef>()}, 
     {"WGPUProcSharedTextureMemoryBeginAccess", get_typedef_handler<WGPUProcSharedTextureMemoryBeginAccess>()}, 
     {"WGPUProcSharedTextureMemoryCreateTexture", get_typedef_handler<WGPUProcSharedTextureMemoryCreateTexture>()}, 
     {"WGPUProcSharedTextureMemoryEndAccess", get_typedef_handler<WGPUProcSharedTextureMemoryEndAccess>()}, 
     {"WGPUProcSharedTextureMemoryEndAccessStateFreeMembers", get_typedef_handler<WGPUProcSharedTextureMemoryEndAccessStateFreeMembers>()}, 
     {"WGPUProcSharedTextureMemoryGetProperties", get_typedef_handler<WGPUProcSharedTextureMemoryGetProperties>()}, 
     {"WGPUProcSharedTextureMemoryIsDeviceLost", get_typedef_handler<WGPUProcSharedTextureMemoryIsDeviceLost>()}, 
     {"WGPUProcSharedTextureMemoryRelease", get_typedef_handler<WGPUProcSharedTextureMemoryRelease>()}, 
     {"WGPUProcSharedTextureMemorySetLabel", get_typedef_handler<WGPUProcSharedTextureMemorySetLabel>()}, 
     {"WGPUProcSupportedFeaturesFreeMembers", get_typedef_handler<WGPUProcSupportedFeaturesFreeMembers>()}, 
     {"WGPUProcSupportedWGSLLanguageFeaturesFreeMembers", get_typedef_handler<WGPUProcSupportedWGSLLanguageFeaturesFreeMembers>()}, 
     {"WGPUProcSurfaceAddRef", get_typedef_handler<WGPUProcSurfaceAddRef>()}, 
     {"WGPUProcSurfaceCapabilitiesFreeMembers", get_typedef_handler<WGPUProcSurfaceCapabilitiesFreeMembers>()}, 
     {"WGPUProcSurfaceConfigure", get_typedef_handler<WGPUProcSurfaceConfigure>()}, 
     {"WGPUProcSurfaceGetCapabilities", get_typedef_handler<WGPUProcSurfaceGetCapabilities>()}, 
     {"WGPUProcSurfaceGetCurrentTexture", get_typedef_handler<WGPUProcSurfaceGetCurrentTexture>()}, 
     {"WGPUProcSurfacePresent", get_typedef_handler<WGPUProcSurfacePresent>()}, 
     {"WGPUProcSurfaceRelease", get_typedef_handler<WGPUProcSurfaceRelease>()}, 
     {"WGPUProcSurfaceSetLabel", get_typedef_handler<WGPUProcSurfaceSetLabel>()}, 
     {"WGPUProcSurfaceUnconfigure", get_typedef_handler<WGPUProcSurfaceUnconfigure>()}, 
     {"WGPUProcTextureAddRef", get_typedef_handler<WGPUProcTextureAddRef>()}, 
     {"WGPUProcTextureCreateErrorView", get_typedef_handler<WGPUProcTextureCreateErrorView>()}, 
     {"WGPUProcTextureCreateView", get_typedef_handler<WGPUProcTextureCreateView>()}, 
     {"WGPUProcTextureDestroy", get_typedef_handler<WGPUProcTextureDestroy>()}, 
     {"WGPUProcTextureGetDepthOrArrayLayers", get_typedef_handler<WGPUProcTextureGetDepthOrArrayLayers>()}, 
     {"WGPUProcTextureGetDimension", get_typedef_handler<WGPUProcTextureGetDimension>()}, 
     {"WGPUProcTextureGetFormat", get_typedef_handler<WGPUProcTextureGetFormat>()}, 
     {"WGPUProcTextureGetHeight", get_typedef_handler<WGPUProcTextureGetHeight>()}, 
     {"WGPUProcTextureGetMipLevelCount", get_typedef_handler<WGPUProcTextureGetMipLevelCount>()}, 
     {"WGPUProcTextureGetSampleCount", get_typedef_handler<WGPUProcTextureGetSampleCount>()}, 
     {"WGPUProcTextureGetUsage", get_typedef_handler<WGPUProcTextureGetUsage>()}, 
     {"WGPUProcTextureGetWidth", get_typedef_handler<WGPUProcTextureGetWidth>()}, 
     {"WGPUProcTextureRelease", get_typedef_handler<WGPUProcTextureRelease>()}, 
     {"WGPUProcTextureSetLabel", get_typedef_handler<WGPUProcTextureSetLabel>()}, 
     {"WGPUProcTextureViewAddRef", get_typedef_handler<WGPUProcTextureViewAddRef>()}, 
     {"WGPUProcTextureViewRelease", get_typedef_handler<WGPUProcTextureViewRelease>()}, 
     {"WGPUProcTextureViewSetLabel", get_typedef_handler<WGPUProcTextureViewSetLabel>()}, 
     {"WGPUQuerySet", get_typedef_handler<WGPUQuerySet>()}, 
     {"WGPUQuerySetDescriptor", get_typedef_handler<WGPUQuerySetDescriptor>()}, 
     {"WGPUQueryType", get_typedef_handler<WGPUQueryType>()}, 
     {"WGPUQueue", get_typedef_handler<WGPUQueue>()}, 
     {"WGPUQueueDescriptor", get_typedef_handler<WGPUQueueDescriptor>()}, 
     {"WGPUQueueWorkDoneCallback", get_typedef_handler<WGPUQueueWorkDoneCallback>()}, 
     {"WGPUQueueWorkDoneCallbackInfo", get_typedef_handler<WGPUQueueWorkDoneCallbackInfo>()}, 
     {"WGPUQueueWorkDoneStatus", get_typedef_handler<WGPUQueueWorkDoneStatus>()}, 
     {"WGPURenderBundle", get_typedef_handler<WGPURenderBundle>()}, 
     {"WGPURenderBundleDescriptor", get_typedef_handler<WGPURenderBundleDescriptor>()}, 
     {"WGPURenderBundleEncoder", get_typedef_handler<WGPURenderBundleEncoder>()}, 
     {"WGPURenderBundleEncoderDescriptor", get_typedef_handler<WGPURenderBundleEncoderDescriptor>()}, 
     {"WGPURenderPassColorAttachment", get_typedef_handler<WGPURenderPassColorAttachment>()}, 
     {"WGPURenderPassDepthStencilAttachment", get_typedef_handler<WGPURenderPassDepthStencilAttachment>()}, 
     {"WGPURenderPassDescriptor", get_typedef_handler<WGPURenderPassDescriptor>()}, 
     {"WGPURenderPassDescriptorExpandResolveRect", get_typedef_handler<WGPURenderPassDescriptorExpandResolveRect>()}, 
     {"WGPURenderPassDescriptorMaxDrawCount", get_typedef_handler<WGPURenderPassDescriptorMaxDrawCount>()}, 
     {"WGPURenderPassDescriptorResolveRect", get_typedef_handler<WGPURenderPassDescriptorResolveRect>()}, 
     {"WGPURenderPassEncoder", get_typedef_handler<WGPURenderPassEncoder>()}, 
     {"WGPURenderPassMaxDrawCount", get_typedef_handler<WGPURenderPassMaxDrawCount>()}, 
     {"WGPURenderPassPixelLocalStorage", get_typedef_handler<WGPURenderPassPixelLocalStorage>()}, 
     {"WGPURenderPassStorageAttachment", get_typedef_handler<WGPURenderPassStorageAttachment>()}, 
     {"WGPURenderPipeline", get_typedef_handler<WGPURenderPipeline>()}, 
     {"WGPURenderPipelineDescriptor", get_typedef_handler<WGPURenderPipelineDescriptor>()}, 
     {"WGPURequestAdapterCallback", get_typedef_handler<WGPURequestAdapterCallback>()}, 
     {"WGPURequestAdapterCallbackInfo", get_typedef_handler<WGPURequestAdapterCallbackInfo>()}, 
     {"WGPURequestAdapterOptions", get_typedef_handler<WGPURequestAdapterOptions>()}, 
     {"WGPURequestAdapterStatus", get_typedef_handler<WGPURequestAdapterStatus>()}, 
     {"WGPURequestAdapterWebGPUBackendOptions", get_typedef_handler<WGPURequestAdapterWebGPUBackendOptions>()}, 
     {"WGPURequestAdapterWebXROptions", get_typedef_handler<WGPURequestAdapterWebXROptions>()}, 
     {"WGPURequestDeviceCallback", get_typedef_handler<WGPURequestDeviceCallback>()}, 
     {"WGPURequestDeviceCallbackInfo", get_typedef_handler<WGPURequestDeviceCallbackInfo>()}, 
     {"WGPURequestDeviceStatus", get_typedef_handler<WGPURequestDeviceStatus>()}, 
     {"WGPUSType", get_typedef_handler<WGPUSType>()}, 
     {"WGPUSampler", get_typedef_handler<WGPUSampler>()}, 
     {"WGPUSamplerBindingLayout", get_typedef_handler<WGPUSamplerBindingLayout>()}, 
     {"WGPUSamplerBindingType", get_typedef_handler<WGPUSamplerBindingType>()}, 
     {"WGPUSamplerDescriptor", get_typedef_handler<WGPUSamplerDescriptor>()}, 
     {"WGPUShaderModule", get_typedef_handler<WGPUShaderModule>()}, 
     {"WGPUShaderModuleCompilationOptions", get_typedef_handler<WGPUShaderModuleCompilationOptions>()}, 
     {"WGPUShaderModuleDescriptor", get_typedef_handler<WGPUShaderModuleDescriptor>()}, 
     {"WGPUShaderModuleSPIRVDescriptor", get_typedef_handler<WGPUShaderModuleSPIRVDescriptor>()}, 
     {"WGPUShaderModuleWGSLDescriptor", get_typedef_handler<WGPUShaderModuleWGSLDescriptor>()}, 
     {"WGPUShaderSourceSPIRV", get_typedef_handler<WGPUShaderSourceSPIRV>()}, 
     {"WGPUShaderSourceWGSL", get_typedef_handler<WGPUShaderSourceWGSL>()}, 
     {"WGPUShaderStage", get_typedef_handler<WGPUShaderStage>()}, 
     {"WGPUSharedBufferMemory", get_typedef_handler<WGPUSharedBufferMemory>()}, 
     {"WGPUSharedBufferMemoryBeginAccessDescriptor", get_typedef_handler<WGPUSharedBufferMemoryBeginAccessDescriptor>()}, 
     {"WGPUSharedBufferMemoryDescriptor", get_typedef_handler<WGPUSharedBufferMemoryDescriptor>()}, 
     {"WGPUSharedBufferMemoryEndAccessState", get_typedef_handler<WGPUSharedBufferMemoryEndAccessState>()}, 
     {"WGPUSharedBufferMemoryProperties", get_typedef_handler<WGPUSharedBufferMemoryProperties>()}, 
     {"WGPUSharedFence", get_typedef_handler<WGPUSharedFence>()}, 
     {"WGPUSharedFenceDXGISharedHandleDescriptor", get_typedef_handler<WGPUSharedFenceDXGISharedHandleDescriptor>()}, 
     {"WGPUSharedFenceDXGISharedHandleExportInfo", get_typedef_handler<WGPUSharedFenceDXGISharedHandleExportInfo>()}, 
     {"WGPUSharedFenceDescriptor", get_typedef_handler<WGPUSharedFenceDescriptor>()}, 
     {"WGPUSharedFenceEGLSyncDescriptor", get_typedef_handler<WGPUSharedFenceEGLSyncDescriptor>()}, 
     {"WGPUSharedFenceEGLSyncExportInfo", get_typedef_handler<WGPUSharedFenceEGLSyncExportInfo>()}, 
     {"WGPUSharedFenceExportInfo", get_typedef_handler<WGPUSharedFenceExportInfo>()}, 
     {"WGPUSharedFenceMTLSharedEventDescriptor", get_typedef_handler<WGPUSharedFenceMTLSharedEventDescriptor>()}, 
     {"WGPUSharedFenceMTLSharedEventExportInfo", get_typedef_handler<WGPUSharedFenceMTLSharedEventExportInfo>()}, 
     {"WGPUSharedFenceSyncFDDescriptor", get_typedef_handler<WGPUSharedFenceSyncFDDescriptor>()}, 
     {"WGPUSharedFenceSyncFDExportInfo", get_typedef_handler<WGPUSharedFenceSyncFDExportInfo>()}, 
     {"WGPUSharedFenceType", get_typedef_handler<WGPUSharedFenceType>()}, 
     {"WGPUSharedFenceVkSemaphoreOpaqueFDDescriptor", get_typedef_handler<WGPUSharedFenceVkSemaphoreOpaqueFDDescriptor>()}, 
     {"WGPUSharedFenceVkSemaphoreOpaqueFDExportInfo", get_typedef_handler<WGPUSharedFenceVkSemaphoreOpaqueFDExportInfo>()}, 
     {"WGPUSharedFenceVkSemaphoreZirconHandleDescriptor", get_typedef_handler<WGPUSharedFenceVkSemaphoreZirconHandleDescriptor>()}, 
     {"WGPUSharedFenceVkSemaphoreZirconHandleExportInfo", get_typedef_handler<WGPUSharedFenceVkSemaphoreZirconHandleExportInfo>()}, 
     {"WGPUSharedTextureMemory", get_typedef_handler<WGPUSharedTextureMemory>()}, 
     {"WGPUSharedTextureMemoryAHardwareBufferDescriptor", get_typedef_handler<WGPUSharedTextureMemoryAHardwareBufferDescriptor>()}, 
     {"WGPUSharedTextureMemoryAHardwareBufferProperties", get_typedef_handler<WGPUSharedTextureMemoryAHardwareBufferProperties>()}, 
     {"WGPUSharedTextureMemoryBeginAccessDescriptor", get_typedef_handler<WGPUSharedTextureMemoryBeginAccessDescriptor>()}, 
     {"WGPUSharedTextureMemoryD3DSwapchainBeginState", get_typedef_handler<WGPUSharedTextureMemoryD3DSwapchainBeginState>()}, 
     {"WGPUSharedTextureMemoryDXGISharedHandleDescriptor", get_typedef_handler<WGPUSharedTextureMemoryDXGISharedHandleDescriptor>()}, 
     {"WGPUSharedTextureMemoryDescriptor", get_typedef_handler<WGPUSharedTextureMemoryDescriptor>()}, 
     {"WGPUSharedTextureMemoryDmaBufDescriptor", get_typedef_handler<WGPUSharedTextureMemoryDmaBufDescriptor>()}, 
     {"WGPUSharedTextureMemoryDmaBufPlane", get_typedef_handler<WGPUSharedTextureMemoryDmaBufPlane>()}, 
     {"WGPUSharedTextureMemoryEGLImageDescriptor", get_typedef_handler<WGPUSharedTextureMemoryEGLImageDescriptor>()}, 
     {"WGPUSharedTextureMemoryEndAccessState", get_typedef_handler<WGPUSharedTextureMemoryEndAccessState>()}, 
     {"WGPUSharedTextureMemoryIOSurfaceDescriptor", get_typedef_handler<WGPUSharedTextureMemoryIOSurfaceDescriptor>()}, 
     {"WGPUSharedTextureMemoryOpaqueFDDescriptor", get_typedef_handler<WGPUSharedTextureMemoryOpaqueFDDescriptor>()}, 
     {"WGPUSharedTextureMemoryProperties", get_typedef_handler<WGPUSharedTextureMemoryProperties>()}, 
     {"WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor", get_typedef_handler<WGPUSharedTextureMemoryVkDedicatedAllocationDescriptor>()}, 
     {"WGPUSharedTextureMemoryVkImageLayoutBeginState", get_typedef_handler<WGPUSharedTextureMemoryVkImageLayoutBeginState>()}, 
     {"WGPUSharedTextureMemoryVkImageLayoutEndState", get_typedef_handler<WGPUSharedTextureMemoryVkImageLayoutEndState>()}, 
     {"WGPUSharedTextureMemoryZirconHandleDescriptor", get_typedef_handler<WGPUSharedTextureMemoryZirconHandleDescriptor>()}, 
     {"WGPUStaticSamplerBindingLayout", get_typedef_handler<WGPUStaticSamplerBindingLayout>()}, 
     {"WGPUStatus", get_typedef_handler<WGPUStatus>()}, 
     {"WGPUStencilFaceState", get_typedef_handler<WGPUStencilFaceState>()}, 
     {"WGPUStencilOperation", get_typedef_handler<WGPUStencilOperation>()}, 
     {"WGPUStorageTextureAccess", get_typedef_handler<WGPUStorageTextureAccess>()}, 
     {"WGPUStorageTextureBindingLayout", get_typedef_handler<WGPUStorageTextureBindingLayout>()}, 
     {"WGPUStoreOp", get_typedef_handler<WGPUStoreOp>()}, 
     {"WGPUStringView", get_typedef_handler<WGPUStringView>()}, 
     {"WGPUSubgroupMatrixComponentType", get_typedef_handler<WGPUSubgroupMatrixComponentType>()}, 
     {"WGPUSubgroupMatrixConfig", get_typedef_handler<WGPUSubgroupMatrixConfig>()}, 
     {"WGPUSupportedFeatures", get_typedef_handler<WGPUSupportedFeatures>()}, 
     {"WGPUSupportedWGSLLanguageFeatures", get_typedef_handler<WGPUSupportedWGSLLanguageFeatures>()}, 
     {"WGPUSurface", get_typedef_handler<WGPUSurface>()}, 
     {"WGPUSurfaceCapabilities", get_typedef_handler<WGPUSurfaceCapabilities>()}, 
     {"WGPUSurfaceColorManagement", get_typedef_handler<WGPUSurfaceColorManagement>()}, 
     {"WGPUSurfaceConfiguration", get_typedef_handler<WGPUSurfaceConfiguration>()}, 
     {"WGPUSurfaceDescriptor", get_typedef_handler<WGPUSurfaceDescriptor>()}, 
     {"WGPUSurfaceDescriptorFromAndroidNativeWindow", get_typedef_handler<WGPUSurfaceDescriptorFromAndroidNativeWindow>()}, 
     {"WGPUSurfaceDescriptorFromMetalLayer", get_typedef_handler<WGPUSurfaceDescriptorFromMetalLayer>()}, 
     {"WGPUSurfaceDescriptorFromWaylandSurface", get_typedef_handler<WGPUSurfaceDescriptorFromWaylandSurface>()}, 
     {"WGPUSurfaceDescriptorFromWindowsCoreWindow", get_typedef_handler<WGPUSurfaceDescriptorFromWindowsCoreWindow>()}, 
     {"WGPUSurfaceDescriptorFromWindowsHWND", get_typedef_handler<WGPUSurfaceDescriptorFromWindowsHWND>()}, 
     {"WGPUSurfaceDescriptorFromWindowsUWPSwapChainPanel", get_typedef_handler<WGPUSurfaceDescriptorFromWindowsUWPSwapChainPanel>()}, 
     {"WGPUSurfaceDescriptorFromWindowsWinUISwapChainPanel", get_typedef_handler<WGPUSurfaceDescriptorFromWindowsWinUISwapChainPanel>()}, 
     {"WGPUSurfaceDescriptorFromXcbWindow", get_typedef_handler<WGPUSurfaceDescriptorFromXcbWindow>()}, 
     {"WGPUSurfaceDescriptorFromXlibWindow", get_typedef_handler<WGPUSurfaceDescriptorFromXlibWindow>()}, 
     {"WGPUSurfaceGetCurrentTextureStatus", get_typedef_handler<WGPUSurfaceGetCurrentTextureStatus>()}, 
     {"WGPUSurfaceSourceAndroidNativeWindow", get_typedef_handler<WGPUSurfaceSourceAndroidNativeWindow>()}, 
     {"WGPUSurfaceSourceMetalLayer", get_typedef_handler<WGPUSurfaceSourceMetalLayer>()}, 
     {"WGPUSurfaceSourceWaylandSurface", get_typedef_handler<WGPUSurfaceSourceWaylandSurface>()}, 
     {"WGPUSurfaceSourceWindowsHWND", get_typedef_handler<WGPUSurfaceSourceWindowsHWND>()}, 
     {"WGPUSurfaceSourceXCBWindow", get_typedef_handler<WGPUSurfaceSourceXCBWindow>()}, 
     {"WGPUSurfaceSourceXlibWindow", get_typedef_handler<WGPUSurfaceSourceXlibWindow>()}, 
     {"WGPUSurfaceTexture", get_typedef_handler<WGPUSurfaceTexture>()}, 
     {"WGPUTexelCopyBufferInfo", get_typedef_handler<WGPUTexelCopyBufferInfo>()}, 
     {"WGPUTexelCopyBufferLayout", get_typedef_handler<WGPUTexelCopyBufferLayout>()}, 
     {"WGPUTexelCopyTextureInfo", get_typedef_handler<WGPUTexelCopyTextureInfo>()}, 
     {"WGPUTexture", get_typedef_handler<WGPUTexture>()}, 
     {"WGPUTextureAspect", get_typedef_handler<WGPUTextureAspect>()}, 
     {"WGPUTextureBindingLayout", get_typedef_handler<WGPUTextureBindingLayout>()}, 
     {"WGPUTextureBindingViewDimensionDescriptor", get_typedef_handler<WGPUTextureBindingViewDimensionDescriptor>()}, 
     {"WGPUTextureDescriptor", get_typedef_handler<WGPUTextureDescriptor>()}, 
     {"WGPUTextureDimension", get_typedef_handler<WGPUTextureDimension>()}, 
     {"WGPUTextureFormat", get_typedef_handler<WGPUTextureFormat>()}, 
     {"WGPUTextureSampleType", get_typedef_handler<WGPUTextureSampleType>()}, 
     {"WGPUTextureUsage", get_typedef_handler<WGPUTextureUsage>()}, 
     {"WGPUTextureView", get_typedef_handler<WGPUTextureView>()}, 
     {"WGPUTextureViewDescriptor", get_typedef_handler<WGPUTextureViewDescriptor>()}, 
     {"WGPUTextureViewDimension", get_typedef_handler<WGPUTextureViewDimension>()}, 
     {"WGPUToneMappingMode", get_typedef_handler<WGPUToneMappingMode>()}, 
     {"WGPUUncapturedErrorCallback", get_typedef_handler<WGPUUncapturedErrorCallback>()}, 
     {"WGPUUncapturedErrorCallbackInfo", get_typedef_handler<WGPUUncapturedErrorCallbackInfo>()}, 
     {"WGPUVertexAttribute", get_typedef_handler<WGPUVertexAttribute>()}, 
     {"WGPUVertexBufferLayout", get_typedef_handler<WGPUVertexBufferLayout>()}, 
     {"WGPUVertexFormat", get_typedef_handler<WGPUVertexFormat>()}, 
     {"WGPUVertexState", get_typedef_handler<WGPUVertexState>()}, 
     {"WGPUVertexStepMode", get_typedef_handler<WGPUVertexStepMode>()}, 
     {"WGPUWGSLLanguageFeatureName", get_typedef_handler<WGPUWGSLLanguageFeatureName>()}, 
     {"WGPUWaitStatus", get_typedef_handler<WGPUWaitStatus>()}, 
     {"WGPUYCbCrVkDescriptor", get_typedef_handler<WGPUYCbCrVkDescriptor>()}, 
     {"int32_t", get_typedef_handler<int32_t>()}, 
     {"size_t", get_typedef_handler<size_t>()}, 
     {"uint16_t", get_typedef_handler<uint16_t>()}, 
     {"uint32_t", get_typedef_handler<uint32_t>()}, 
     {"uint64_t", get_typedef_handler<uint64_t>()}, 
     {"uint8_t", get_typedef_handler<uint8_t>()}
}};
