// SPDX-License-Identifier: MIT
//
// The ycetl path: take the constexpr API tree (webgpu_tree.hpp) and rebuild
// the Python ctypes bindings FROM IT, entirely at constant-evaluation time,
// using ycetl's constexpr string (a multitype_memory-backed dynamic_array of
// char as WORKING memory). The finished text is copied into a fixed-size
// std::array<char, CAP> — the RESULT memory — which the compiler bakes into
// .rodata. main() just writes that baked blob to disk.
//
// This mirrors webgpu_introspect's own emit_python byte-for-byte, so the two
// paths (libclang tool → .py, and tree → ycetl → .py) produce identical files.

#include <array>
#include <cstddef>
#include <cstdio>
#include <string_view>

#include <ycetl/memory.hpp>
#include <ycetl/string.hpp>

#include "webgpu_tree.hpp"

namespace {

// Generously sized result buffer (the direct bindings are ~150 KB).
constexpr std::size_t CAP = 262144;

struct baked {
  std::size_t len;
  std::array<char, CAP> data;
};

constexpr void put_int(ycetl::string &s, long long v) {
  if (v == 0) {
    s.push_back('0');
    return;
  }
  bool neg = v < 0;
  unsigned long long u = neg ? (unsigned long long)(-(v + 1)) + 1ull
                             : (unsigned long long)v;
  char tmp[24];
  int n = 0;
  while (u) {
    tmp[n++] = char('0' + (u % 10));
    u /= 10;
  }
  if (neg)
    s.push_back('-');
  while (n)
    s.push_back(tmp[--n]);
}

// Build the Python module text into `s`, reproducing emit_python exactly.
constexpr void build_into(ycetl::string &s) {
  using namespace webgpu_tree;

  s.append("# Generated by webgpu_introspect. Do not edit by hand.\n"
           "# Source: webgpu.h\n"
           "from ctypes import (\n"
           "    Structure, CFUNCTYPE, POINTER,\n"
           "    c_bool, c_char, c_byte, c_ubyte,\n"
           "    c_short, c_ushort, c_int, c_uint,\n"
           "    c_long, c_ulong, c_longlong, c_ulonglong,\n"
           "    c_int8, c_int16, c_int32, c_int64,\n"
           "    c_uint8, c_uint16, c_uint32, c_uint64,\n"
           "    c_float, c_double, c_size_t, c_void_p,\n"
           ")\n"
           "from enum import IntEnum\n\n");

  // Enums.
  for (const auto &e : enums) {
    s.append("class ");
    s.append(e.name);
    s.append("(IntEnum):\n");
    if (e.value_count == 0) {
      s.append("    pass\n\n");
      continue;
    }
    for (std::size_t i = 0; i < e.value_count; ++i) {
      const auto &v = enum_values[e.value_begin + i];
      if (v.is_alias) {
        s.append("    # ");
        s.append(v.name);
        s.append(" = ");
        put_int(s, v.value);
        s.append("  (alias)\n");
      } else {
        s.append("    ");
        s.append(v.name);
        s.append(" = ");
        put_int(s, v.value);
        s.append("\n");
      }
    }
    s.append("\n");
  }

  // Constants.
  if (constants.size() != 0) {
    s.append("# Flag and sentinel constants.\n");
    for (const auto &c : constants) {
      s.append(c.name);
      s.append(" = ");
      s.append(c.value);
      s.append("\n");
    }
    s.append("\n");
  }

  // Struct forward declarations (name order).
  for (const auto &r : records) {
    s.append("class ");
    s.append(r.name);
    s.append("(Structure): pass\n");
  }
  s.append("\n");

  // Typedef aliases.
  for (const auto &a : aliases) {
    s.append(a.name);
    s.append(" = ");
    s.append(a.ctype);
    s.append("\n");
  }
  s.append("\n");

  // Struct field tables (topological order).
  for (std::size_t t = 0; t < topo.size(); ++t) {
    const auto &r = records[topo[t]];
    if (r.opaque) {
      s.append("# ");
      s.append(r.name);
      s.append(": opaque (no layout exposed)\n");
      continue;
    }
    s.append(r.name);
    s.append("._fields_ = [\n");
    for (std::size_t i = 0; i < r.field_count; ++i) {
      const auto &f = fields[r.field_begin + i];
      s.append("    (\"");
      s.append(f.name);
      s.append("\", ");
      s.append(f.ctype);
      s.append("),  # offset=");
      put_int(s, f.offset_bytes);
      s.append(" size=");
      put_int(s, f.size_bytes);
      s.append(" src=");
      s.append(f.src);
      s.append("\n");
    }
    s.append("]\n\n");
  }

  // Callback types.
  s.append("# Callback types — wrap a Python function: cb = WGPUFooCallback(fn)\n");
  for (const auto &c : callbacks) {
    s.append(c.name);
    s.append(" = CFUNCTYPE(");
    s.append(c.ret);
    for (std::size_t i = 0; i < c.arg_count; ++i) {
      s.append(", ");
      s.append(callback_args[c.arg_begin + i]);
    }
    s.append(")\n");
  }
  s.append("\n");

  // Function table.
  s.append("_FUNCTIONS = [\n");
  for (const auto &f : functions) {
    s.append("    (\"");
    s.append(f.name);
    s.append("\", ");
    s.append(f.ret);
    s.append(", [");
    for (std::size_t i = 0; i < f.arg_count; ++i) {
      if (i)
        s.append(", ");
      s.append(function_args[f.arg_begin + i]);
    }
    s.append("]),\n");
  }
  s.append("]\n\n");

  s.append("def load(path):\n"
           "    \"\"\"dlopen the WebGPU library and bind every function with its\n"
           "    ctypes restype/argtypes. Returns the ctypes.CDLL.\"\"\"\n"
           "    import ctypes\n"
           "    lib = ctypes.CDLL(path)\n"
           "    for name, restype, argtypes in _FUNCTIONS:\n"
           "        try:\n"
           "            fn = getattr(lib, name)\n"
           "        except AttributeError:\n"
           "            continue  # symbol not exported by this build\n"
           "        fn.restype = restype\n"
           "        fn.argtypes = argtypes\n"
           "    return lib\n");
}

// Working memory (ycetl string) → result memory (baked char array).
constexpr baked build() {
  baked out{};
  ycetl::default_memory<char> mem;
  ycetl::string s(mem);
  build_into(s);
  out.len = s.size();
  std::size_t i = 0;
  for (char c : s)
    if (i < CAP)
      out.data[i++] = c;
  return out;
}

// The whole Python module, computed at compile time, living in .rodata.
constexpr baked PY = build();

} // namespace

int main(int argc, char **argv) {
  const char *path = argc > 1 ? argv[1] : "webgpu_ctypes_from_tree.py";
  std::FILE *f = std::fopen(path, "wb");
  if (!f) {
    std::fprintf(stderr, "cannot open %s\n", path);
    return 1;
  }
  std::fwrite(PY.data.data(), 1, PY.len, f);
  std::fclose(f);
  std::fprintf(stderr, "webgpu_emit_py: wrote %zu bytes to %s\n", PY.len, path);
  return 0;
}
